package com.apps.sky.cryptoticker.Global;

import java.util.HashMap;

/**
 * Created by subyadav on 26/10/17.
 */

public class ConstantsCrypto {
    public static final HashMap<String, String[]> cryptoMap = new HashMap<>();

    static {
        cryptoMap.put("bitcoin", new String[]{"Bitcoin", "BTC"});
        cryptoMap.put("ethereum", new String[]{"Ethereum", "ETH"});
        cryptoMap.put("bitcoin_cash", new String[]{"Bitcoin Cash", "BCH"});
        cryptoMap.put("ripple", new String[]{"Ripple", "XRP"});
        cryptoMap.put("litecoin", new String[]{"Litecoin", "LTC"});
        cryptoMap.put("cardano", new String[]{"Cardano", "ADA"});
        cryptoMap.put("iota", new String[]{"IOTA", "MIOTA"});
        cryptoMap.put("dash", new String[]{"Dash", "DASH"});
        cryptoMap.put("nem", new String[]{"NEM", "XEM"});
        cryptoMap.put("bitcoin_gold", new String[]{"Bitcoin Gold", "BTG"});
        cryptoMap.put("monero", new String[]{"Monero", "XMR"});
        cryptoMap.put("eos", new String[]{"EOS", "EOS"});
        cryptoMap.put("qtum", new String[]{"Qtum", "QTUM"});
        cryptoMap.put("stellar", new String[]{"Stellar", "XLM"});
        cryptoMap.put("neo", new String[]{"NEO", "NEO"});
        cryptoMap.put("verge", new String[]{"Verge", "XVG"});
        cryptoMap.put("ethereum_classic", new String[]{"Ethereum Classic", "ETC"});
        cryptoMap.put("tron", new String[]{"TRON", "TRX"});
        cryptoMap.put("lisk", new String[]{"Lisk", "LSK"});
        cryptoMap.put("nxt", new String[]{"Nxt", "NXT"});
        cryptoMap.put("ardor", new String[]{"Ardor", "ARDR"});
        cryptoMap.put("omisego", new String[]{"OmiseGO", "OMG"});
        cryptoMap.put("zcash", new String[]{"Zcash", "ZEC"});
        cryptoMap.put("bitshares", new String[]{"BitShares", "BTS"});
        cryptoMap.put("bitconnect", new String[]{"BitConnect", "BCC"});
        cryptoMap.put("populous", new String[]{"Populous", "PPT"});
        cryptoMap.put("waves", new String[]{"Waves", "WAVES"});
        cryptoMap.put("stratis", new String[]{"Stratis", "STRAT"});
        cryptoMap.put("tether", new String[]{"Tether", "USDT"});
        cryptoMap.put("bytecoin_bcn", new String[]{"Bytecoin", "BCN"});
        cryptoMap.put("hshare", new String[]{"Hshare", "HSR"});
        cryptoMap.put("dogecoin", new String[]{"Dogecoin", "DOGE"});
        cryptoMap.put("siacoin", new String[]{"Siacoin", "SC"});
        cryptoMap.put("komodo", new String[]{"Komodo", "KMD"});
        cryptoMap.put("steem", new String[]{"Steem", "STEEM"});
        cryptoMap.put("digibyte", new String[]{"DigiByte", "DGB"});
        cryptoMap.put("augur", new String[]{"Augur", "REP"});
        cryptoMap.put("veritaseum", new String[]{"Veritaseum", "VERI"});
        cryptoMap.put("raiblocks", new String[]{"RaiBlocks", "XRB"});
        cryptoMap.put("pivx", new String[]{"PIVX", "PIVX"});
        cryptoMap.put("ark", new String[]{"Ark", "ARK"});
        cryptoMap.put("monacoin", new String[]{"MonaCoin", "MONA"});
        cryptoMap.put("reddcoin", new String[]{"ReddCoin", "RDD"});
        cryptoMap.put("decred", new String[]{"Decred", "DCR"});
        cryptoMap.put("golem_network_tokens", new String[]{"Golem", "GNT"});
        cryptoMap.put("salt", new String[]{"SALT", "SALT"});
        cryptoMap.put("binance_coin", new String[]{"Binance Coin", "BNB"});
        cryptoMap.put("status", new String[]{"Status", "SNT"});
        cryptoMap.put("tenx", new String[]{"TenX", "PAY"});
        cryptoMap.put("electroneum", new String[]{"Electroneum", "ETN"});
        cryptoMap.put("byteball", new String[]{"Byteball Bytes", "GBYTE"});
        cryptoMap.put("bitcoindark", new String[]{"BitcoinDark", "BTCD"});
        cryptoMap.put("santiment", new String[]{"Santiment Network Token", "SAN"});
        cryptoMap.put("basic_attention_token", new String[]{"Basic Attention Token", "BAT"});
        cryptoMap.put("maidsafecoin", new String[]{"MaidSafeCoin", "MAID"});
        cryptoMap.put("zcoin", new String[]{"ZCoin", "XZC"});
        cryptoMap.put("vechain", new String[]{"VeChain", "VET"});
        cryptoMap.put("walton", new String[]{"Walton", "WTC"});
        cryptoMap.put("civic", new String[]{"Civic", "CVC"});
        cryptoMap.put("bytom", new String[]{"Bytom", "BTM"});
        cryptoMap.put("syscoin", new String[]{"Syscoin", "SYS"});
        cryptoMap.put("kyber_network", new String[]{"Kyber Network", "KNC"});
        cryptoMap.put("power_ledger", new String[]{"Power Ledger", "POWR"});
        cryptoMap.put("digixdao", new String[]{"DigixDAO", "DGD"});
        cryptoMap.put("factom", new String[]{"Factom", "FCT"});
        cryptoMap.put("qash", new String[]{"QASH", "QASH"});
        cryptoMap.put("vertcoin", new String[]{"Vertcoin", "VTC"});
        cryptoMap.put("aeternity", new String[]{"Aeternity", "AE"});
        cryptoMap.put("gas", new String[]{"Gas", "GAS"});
        cryptoMap.put("gamecredits", new String[]{"GameCredits", "GAME"});
        cryptoMap.put("funfair", new String[]{"FunFair", "FUN"});
        cryptoMap.put("bitbay", new String[]{"BitBay", "BAY"});
        cryptoMap.put("monaco", new String[]{"Monaco", "MCO"});
        cryptoMap.put("aion", new String[]{"Aion", "AION"});
        cryptoMap.put("cryptonex", new String[]{"Cryptonex", "CNX"});
        cryptoMap.put("ethos", new String[]{"Ethos", "ETHOS"});
        cryptoMap.put("gnosis_gno", new String[]{"Gnosis", "GNO"});
        cryptoMap.put("dragonchain", new String[]{"Dragonchain", "DRGN"});
        cryptoMap.put("iconomi", new String[]{"Iconomi", "ICN"});
        cryptoMap.put("einsteinium", new String[]{"Einsteinium", "EMC2"});
        cryptoMap.put("decentraland", new String[]{"Decentraland", "MANA"});
        cryptoMap.put("gxshares", new String[]{"GXShares", "GXS"});
        cryptoMap.put("dent", new String[]{"Dent", "DENT"});
        cryptoMap.put("chainlink", new String[]{"ChainLink", "LINK"});
        cryptoMap.put("nexus", new String[]{"Nexus", "NXS"});
        cryptoMap.put("substratum", new String[]{"Substratum", "SUB"});
        cryptoMap.put("request_network", new String[]{"Request Network", "REQ"});
        cryptoMap.put("singulardtv", new String[]{"SingularDTV", "SNGLS"});
        cryptoMap.put("edgeless", new String[]{"Edgeless", "EDG"});
        cryptoMap.put("blocknet", new String[]{"Blocknet", "BLOCK"});
        cryptoMap.put("digitalnote", new String[]{"DigitalNote", "XDN"});
        cryptoMap.put("sonm", new String[]{"SONM", "SNM"});
        cryptoMap.put("ubiq", new String[]{"Ubiq", "UBQ"});
        cryptoMap.put("raiden_network_token", new String[]{"Raiden Network Token", "RDN"});
        cryptoMap.put("bancor", new String[]{"Bancor", "BNT"});
        cryptoMap.put("centra", new String[]{"Centra", "CTR"});
        cryptoMap.put("nav_coin", new String[]{"NAV Coin", "NAV"});
        cryptoMap.put("metal", new String[]{"Metal", "MTL"});
        cryptoMap.put("storj", new String[]{"Storj", "STORJ"});
        cryptoMap.put("time_new_bank", new String[]{"Time New Bank", "TNB"});
        cryptoMap.put("streamr_datacoin", new String[]{"Streamr DATAcoin", "DATA"});
        cryptoMap.put("groestlcoin", new String[]{"Groestlcoin", "GRS"});
        cryptoMap.put("paypie", new String[]{"PayPie", "PPP"});
        cryptoMap.put("adx_net", new String[]{"AdEx", "ADX"});
        cryptoMap.put("particl", new String[]{"Particl", "PART"});
        cryptoMap.put("asch", new String[]{"Asch", "XAS"});
        cryptoMap.put("ripio_credit_network", new String[]{"Ripio Credit Network", "RCN"});
        cryptoMap.put("zencash", new String[]{"ZenCash", "ZEN"});
        cryptoMap.put("aragon", new String[]{"Aragon", "ANT"});
        cryptoMap.put("burst", new String[]{"Burst", "BURST"});
        cryptoMap.put("skycoin", new String[]{"Skycoin", "SKY"});
        cryptoMap.put("cloakcoin", new String[]{"CloakCoin", "CLOAK"});
        cryptoMap.put("agoras_tokens", new String[]{"Agoras Tokens", "AGRS"});
        cryptoMap.put("enigma_project", new String[]{"Enigma", "ENG"});
        cryptoMap.put("emercoin", new String[]{"Emercoin", "EMC"});
        cryptoMap.put("peercoin", new String[]{"Peercoin", "PPC"});
        cryptoMap.put("ink", new String[]{"Ink", "INK"});
        cryptoMap.put("enjin_coin", new String[]{"Enjin Coin", "ENJ"});
        cryptoMap.put("xtrabytes", new String[]{"XTRABYTES", "XBY"});
        cryptoMap.put("salus", new String[]{"SaluS", "SLS"});
        cryptoMap.put("metaverse", new String[]{"Metaverse ETP", "ETP"});
        cryptoMap.put("quantstamp", new String[]{"Quantstamp", "QSP"});
        cryptoMap.put("achain", new String[]{"Achain", "ACT"});
        cryptoMap.put("kin", new String[]{"Kin", "KIN"});
        cryptoMap.put("voxels", new String[]{"Voxels", "VOX"});
        cryptoMap.put("smartcash", new String[]{"SmartCash", "SMART"});
        cryptoMap.put("revain", new String[]{"Revain", "R"});
        cryptoMap.put("library_credit", new String[]{"LBRY Credits", "LBC"});
        cryptoMap.put("wings", new String[]{"Wings", "WINGS"});
        cryptoMap.put("wabi", new String[]{"WaBi", "WABI"});
        cryptoMap.put("kucoin_shares", new String[]{"KuCoin Shares", "KCS"});
        cryptoMap.put("loopring", new String[]{"Loopring", "LRC"});
        cryptoMap.put("rchain", new String[]{"RChain", "RHOC"});
        cryptoMap.put("triggers", new String[]{"Triggers", "TRIG"});
        cryptoMap.put("quantum_resistant_ledger", new String[]{"Quantum Resistant Ledger", "QRL"});
        cryptoMap.put("pura", new String[]{"Pura", "PURA"});
        cryptoMap.put("red_pulse", new String[]{"Red Pulse", "RPX"});
        cryptoMap.put("mobilego", new String[]{"MobileGo", "MGO"});
        cryptoMap.put("cofound_it", new String[]{"Cofound.it", "CFI"});
        cryptoMap.put("neblio", new String[]{"Neblio", "NEBL"});
        cryptoMap.put("counterparty", new String[]{"Counterparty", "XCP"});
        cryptoMap.put("rise", new String[]{"Rise", "RISE"});
        cryptoMap.put("hempcoin", new String[]{"HempCoin", "THC"});
        cryptoMap.put("viberate", new String[]{"Viberate", "VIB"});
        cryptoMap.put("feathercoin", new String[]{"Feathercoin", "FTC"});
        cryptoMap.put("rlc", new String[]{"iExec RLC", "RLC"});
        cryptoMap.put("melon", new String[]{"Melon", "MLN"});
        cryptoMap.put("viacoin", new String[]{"Viacoin", "VIA"});
        cryptoMap.put("shift", new String[]{"Shift", "SHIFT"});
        cryptoMap.put("delphy", new String[]{"Delphy", "DPY"});
        cryptoMap.put("attention_token_of_media", new String[]{"ATMChain", "ATM"});
        cryptoMap.put("supernet_unity", new String[]{"SuperNET", "UNITY"});
        cryptoMap.put("wagerr", new String[]{"Wagerr", "WGR"});
        cryptoMap.put("firstblood", new String[]{"FirstBlood", "1ST"});
        cryptoMap.put("gulden", new String[]{"Gulden", "NLG"});
        cryptoMap.put("cindicator", new String[]{"Cindicator", "CND"});
        cryptoMap.put("poet", new String[]{"Po.et", "POE"});
        cryptoMap.put("pillar", new String[]{"Pillar", "PLR"});
        cryptoMap.put("sibcoin", new String[]{"SIBCoin", "SIB"});
        cryptoMap.put("potcoin", new String[]{"PotCoin", "POT"});
        cryptoMap.put("mercury", new String[]{"Mercury", "MER"});
        cryptoMap.put("minexcoin", new String[]{"MinexCoin", "MNX"});
        cryptoMap.put("humaniq", new String[]{"Humaniq", "HMQ"});
        cryptoMap.put("decent", new String[]{"DECENT", "DCT"});
        cryptoMap.put("yoyow", new String[]{"YOYOW", "YOYOW"});
        cryptoMap.put("airswap", new String[]{"AirSwap", "AST"});
        cryptoMap.put("dentacoin", new String[]{"Dentacoin", "DCN"});
        cryptoMap.put("eidoo", new String[]{"Eidoo", "EDO"});
        cryptoMap.put("whitecoin", new String[]{"WhiteCoin", "XWC"});
        cryptoMap.put("storm", new String[]{"Storm", "STORM"});
        cryptoMap.put("pepe_cash", new String[]{"Pepe Cash", "PEPECASH"});
        cryptoMap.put("district0x", new String[]{"district0x", "DNT"});
        cryptoMap.put("shield_xsh", new String[]{"SHIELD", "XSH"});
        cryptoMap.put("cobinhood", new String[]{"Cobinhood", "COB"});
        cryptoMap.put("faircoin", new String[]{"FairCoin", "FAIR"});
        cryptoMap.put("iocoin", new String[]{"I/O Coin", "IOC"});
        cryptoMap.put("ethlend", new String[]{"ETHLend", "LEND"});
        cryptoMap.put("lykke", new String[]{"Lykke", "LKK"});
        cryptoMap.put("elastic", new String[]{"Elastic", "XEL"});
        cryptoMap.put("aeon", new String[]{"Aeon", "AEON"});
        cryptoMap.put("xplay", new String[]{"XPlay", "XPA"});
        cryptoMap.put("synereo", new String[]{"Synereo", "AMP"});
        cryptoMap.put("tierion", new String[]{"Tierion", "TNT"});
        cryptoMap.put("namecoin", new String[]{"Namecoin", "NMC"});
        cryptoMap.put("ion", new String[]{"ION", "ION"});
        cryptoMap.put("blockv", new String[]{"BLOCKv", "VEE"});
        cryptoMap.put("etherparty", new String[]{"Etherparty", "FUEL"});
        cryptoMap.put("modum", new String[]{"Modum", "MOD"});
        cryptoMap.put("xp", new String[]{"XP", "XP"});
        cryptoMap.put("bitcny", new String[]{"bitCNY", "BITCNY"});
        cryptoMap.put("coindash", new String[]{"CoinDash", "CDT"});
        cryptoMap.put("blackcoin", new String[]{"BlackCoin", "BLK"});
        cryptoMap.put("amber", new String[]{"Ambrosus", "AMB"});
        cryptoMap.put("simple_token", new String[]{"Simple Token", "OST"});
        cryptoMap.put("bitbean", new String[]{"BitBean", "BITB"});
        cryptoMap.put("crown", new String[]{"Crown", "CRW"});
        cryptoMap.put("taas", new String[]{"TaaS", "TAAS"});
        cryptoMap.put("nuls", new String[]{"Nuls", "NULS"});
        cryptoMap.put("waves_community_token", new String[]{"Waves Community Token", "WCT"});
        cryptoMap.put("trust", new String[]{"WeTrust", "TRST"});
        cryptoMap.put("guppy", new String[]{"Matchpool", "GUP"});
        cryptoMap.put("blocktix", new String[]{"Blocktix", "TIX"});
        cryptoMap.put("monetha", new String[]{"Monetha", "MTH"});
        cryptoMap.put("paragon", new String[]{"Paragon", "PRG"});
        cryptoMap.put("okcash", new String[]{"OKCash", "OK"});
        cryptoMap.put("diamond", new String[]{"Diamond", "DMD"});
        cryptoMap.put("unikoin_gold", new String[]{"Unikoin Gold", "UKG"});
        cryptoMap.put("gridcoin", new String[]{"GridCoin", "GRC"});
        cryptoMap.put("agrello_delta", new String[]{"Agrello", "DLT"});
        cryptoMap.put("mysterium", new String[]{"Mysterium", "MYST"});
        cryptoMap.put("radium", new String[]{"Radium", "RADS"});
        cryptoMap.put("moeda_loyalty_points", new String[]{"Moeda Loyalty Points", "MDA"});
        cryptoMap.put("spankchain", new String[]{"SpankChain", "SPANK"});
        cryptoMap.put("monetaryunit", new String[]{"MonetaryUnit", "MUE"});
        cryptoMap.put("bodhi", new String[]{"Bodhi", "BOT"});
        cryptoMap.put("paypex", new String[]{"Paypex", "PAYX"});
        cryptoMap.put("steem_dollars", new String[]{"Steem Dollars", "SBD"});
        cryptoMap.put("expanse", new String[]{"Expanse", "EXP"});
        cryptoMap.put("numeraire", new String[]{"Numeraire", "NMR"});
        cryptoMap.put("adtoken", new String[]{"adToken", "ADT"});
        cryptoMap.put("myriad", new String[]{"Myriad", "XMY"});
        cryptoMap.put("omni", new String[]{"Omni", "OMNI"});
        cryptoMap.put("patientory", new String[]{"Patientory", "PTOY"});
        cryptoMap.put("everex", new String[]{"Everex", "EVX"});
        cryptoMap.put("presearch", new String[]{"Presearch", "PRE"});
        cryptoMap.put("foldingcoin", new String[]{"FoldingCoin", "FLDC"});
        cryptoMap.put("open_trading_network", new String[]{"Open Trading Network", "OTN"});
        cryptoMap.put("bridgecoin", new String[]{"BridgeCoin", "BCO"});
        cryptoMap.put("hive", new String[]{"Hive", "HVN"});
        cryptoMap.put("jinn", new String[]{"Jinn", "JINN"});
        cryptoMap.put("zeusshield", new String[]{"Zeusshield", "ZSC"});
        cryptoMap.put("pascal_coin", new String[]{"Pascal Coin", "PASC"});
        cryptoMap.put("bitcore", new String[]{"Bitcore", "BTX"});
        cryptoMap.put("grid", new String[]{"Grid+", "GRID"});
        cryptoMap.put("phore", new String[]{"Phore", "PHR"});
        cryptoMap.put("golos", new String[]{"Golos", "GOLOS"});
        cryptoMap.put("rubycoin", new String[]{"Rubycoin", "RBY"});
        cryptoMap.put("spectrecoin", new String[]{"Spectrecoin", "XSPEC"});
        cryptoMap.put("swarm_city", new String[]{"Swarm City", "SWT"});
        cryptoMap.put("quantum", new String[]{"Quantum", "QAU"});
        cryptoMap.put("bcap", new String[]{"BCAP", "BCAP"});
        cryptoMap.put("stealthcoin", new String[]{"Stealthcoin", "XST"});
        cryptoMap.put("vericoin", new String[]{"VeriCoin", "VRC"});
        cryptoMap.put("aventus", new String[]{"Aventus", "AVT"});
        cryptoMap.put("genesis_vision", new String[]{"Genesis Vision", "GVT"});
        cryptoMap.put("lunyr", new String[]{"Lunyr", "LUN"});
        cryptoMap.put("oraclechain", new String[]{"OracleChain", "OCT"});
        cryptoMap.put("nolimitcoin", new String[]{"NoLimitCoin", "NLC2"});
        cryptoMap.put("florincoin", new String[]{"FlorinCoin", "FLO"});
        cryptoMap.put("primas", new String[]{"Primas", "PST"});
        cryptoMap.put("circuits_of_value", new String[]{"Circuits of Value", "COVAL"});
        cryptoMap.put("nimiq", new String[]{"Nimiq", "NET"});
        cryptoMap.put("peerplays_ppy", new String[]{"Peerplays", "PPY"});
        cryptoMap.put("russian_mining_coin", new String[]{"Russian Miner Coin", "RMC"});
        cryptoMap.put("global_currency_reserve", new String[]{"Global Currency Reserve", "GCR"});
        cryptoMap.put("mooncoin", new String[]{"Mooncoin", "MOON"});
        cryptoMap.put("clams", new String[]{"Clams", "CLAM"});
        cryptoMap.put("suncontract", new String[]{"SunContract", "SNC"});
        cryptoMap.put("decision_token", new String[]{"Decision Token", "HST"});
        cryptoMap.put("databits", new String[]{"Databits", "DTB"});
        cryptoMap.put("energycoin", new String[]{"Energycoin", "ENRG"});
        cryptoMap.put("lomocoin", new String[]{"LoMoCoin", "LMC"});
        cryptoMap.put("firstcoin", new String[]{"FirstCoin", "FRST"});
        cryptoMap.put("nexium", new String[]{"Nexium", "NXC"});
        cryptoMap.put("obits", new String[]{"OBITS", "OBITS"});
        cryptoMap.put("gambit", new String[]{"Gambit", "GAM"});
        cryptoMap.put("blackmoon_crypto", new String[]{"Blackmoon Crypto", "BMC"});
        cryptoMap.put("bitdice", new String[]{"BitDice", "CSNO"});
        cryptoMap.put("stox", new String[]{"Stox", "STX"});
        cryptoMap.put("mothership", new String[]{"Mothership", "MSP"});
        cryptoMap.put("virtacoin", new String[]{"Virtacoin", "VTA"});
        cryptoMap.put("vibe", new String[]{"VIBE", "VIBE"});
        cryptoMap.put("bitusd", new String[]{"bitUSD", "BITUSD"});
        cryptoMap.put("heat_ledger", new String[]{"HEAT", "HEAT"});
        cryptoMap.put("neoscoin", new String[]{"NeosCoin", "NEOS"});
        cryptoMap.put("musicoin", new String[]{"Musicoin", "MUSIC"});
        cryptoMap.put("bitsend", new String[]{"BitSend", "BSD"});
        cryptoMap.put("htmlcoin", new String[]{"HTMLCOIN", "HTML5"});
        cryptoMap.put("artbyte", new String[]{"ArtByte", "ABY"});
        cryptoMap.put("transfercoin", new String[]{"TransferCoin", "TX"});
        cryptoMap.put("rialto", new String[]{"Rialto", "XRL"});
        cryptoMap.put("tokencard", new String[]{"TokenCard", "TKN"});
        cryptoMap.put("icos", new String[]{"ICOS", "ICOS"});
        cryptoMap.put("pinkcoin", new String[]{"PinkCoin", "PINK"});
        cryptoMap.put("solarcoin", new String[]{"SolarCoin", "SLR"});
        cryptoMap.put("leocoin", new String[]{"LEOcoin", "LEO"});
        cryptoMap.put("soarcoin", new String[]{"Soarcoin", "SOAR"});
        cryptoMap.put("ethereum_blue", new String[]{"BLUE", "BLUE"});
        cryptoMap.put("polybius", new String[]{"Polybius", "PLBT"});
        cryptoMap.put("vcash", new String[]{"Vcash", "XVC"});
        cryptoMap.put("xaurum", new String[]{"Xaurum", "XAUR"});
        cryptoMap.put("incent", new String[]{"Incent", "INCNT"});
        cryptoMap.put("domraider", new String[]{"DomRaider", "DRT"});
        cryptoMap.put("alis", new String[]{"ALIS", "ALIS"});
        cryptoMap.put("bitqy", new String[]{"bitqy", "BQ"});
        cryptoMap.put("airtoken", new String[]{"AirToken", "AIR"});
        cryptoMap.put("exchange_union", new String[]{"Exchange Union", "XUC"});
        cryptoMap.put("dimecoin", new String[]{"Dimecoin", "DIME"});
        cryptoMap.put("sphere", new String[]{"Sphere", "SPHR"});
        cryptoMap.put("etheroll", new String[]{"Etheroll", "DICE"});
        cryptoMap.put("newyorkcoin", new String[]{"NewYorkCoin", "NYC"});
        cryptoMap.put("ixledger", new String[]{"iXledger", "IXT"});
        cryptoMap.put("sequence", new String[]{"Sequence", "SEQ"});
        cryptoMap.put("eccoin", new String[]{"ECC", "ECC"});
        cryptoMap.put("atbcoin", new String[]{"ATBCoin", "ATB"});
        cryptoMap.put("posw_coin", new String[]{"PoSW Coin", "POSW"});
        cryptoMap.put("bitcrystals", new String[]{"Bitcrystals", "BCY"});
        cryptoMap.put("mintcoin", new String[]{"Mintcoin", "MINT"});
        cryptoMap.put("blockmason", new String[]{"BlockMason Credit Protocol", "BCPT"});
        cryptoMap.put("blitzcash", new String[]{"Blitzcash", "BLITZ"});
        cryptoMap.put("obsidian", new String[]{"Obsidian", "ODN"});
        cryptoMap.put("exclusivecoin", new String[]{"ExclusiveCoin", "EXCL"});
        cryptoMap.put("unobtanium", new String[]{"Unobtanium", "UNO"});
        cryptoMap.put("nushares", new String[]{"NuShares", "NSR"});
        cryptoMap.put("oax", new String[]{"OAX", "OAX"});
        cryptoMap.put("kickico", new String[]{"KickCoin", "KICK"});
        cryptoMap.put("coss", new String[]{"COSS", "COSS"});
        cryptoMap.put("nvo", new String[]{"NVO", "NVST"});
        cryptoMap.put("change", new String[]{"Change", "CAG"});
        cryptoMap.put("boolberry", new String[]{"Boolberry", "BBR"});
        cryptoMap.put("universal_currency", new String[]{"Universal Currency", "UNIT"});
        cryptoMap.put("the_champcoin", new String[]{"The ChampCoin", "TCC"});
        cryptoMap.put("curecoin", new String[]{"Curecoin", "CURE"});
        cryptoMap.put("chronobank", new String[]{"Chronobank", "TIME"});
        cryptoMap.put("astro", new String[]{"Astro", "ASTRO"});
        cryptoMap.put("zclassic", new String[]{"ZClassic", "ZCL"});
        cryptoMap.put("fedoracoin", new String[]{"FedoraCoin", "TIPS"});
        cryptoMap.put("bismuth", new String[]{"Bismuth", "BIS"});
        cryptoMap.put("syndicate", new String[]{"Syndicate", "SYNX"});
        cryptoMap.put("bitzeny", new String[]{"Bitzeny", "ZNY"});
        cryptoMap.put("korecoin", new String[]{"Kore", "KORE"});
        cryptoMap.put("deeponion", new String[]{"DeepOnion", "ONION"});
        cryptoMap.put("oxycoin", new String[]{"Oxycoin", "OXY"});
        cryptoMap.put("primecoin", new String[]{"Primecoin", "XPM"});
        cryptoMap.put("dopecoin", new String[]{"DopeCoin", "DOPE"});
        cryptoMap.put("memetic", new String[]{"Memetic / PepeCoin", "MEME"});
        cryptoMap.put("bitmark", new String[]{"Bitmark", "BTM"});
        cryptoMap.put("latoken", new String[]{"LAToken", "LA"});
        cryptoMap.put("maecenas", new String[]{"Maecenas", "ART"});
        cryptoMap.put("encrypgen", new String[]{"EncrypGen", "DNA"});
        cryptoMap.put("decent_bet", new String[]{"DecentBet", "DBET"});
        cryptoMap.put("target_coin", new String[]{"Target Coin", "TGT"});
        cryptoMap.put("pesetacoin", new String[]{"Pesetacoin", "PTC"});
        cryptoMap.put("atmos", new String[]{"Atmos", "ATMS"});
        cryptoMap.put("aeron", new String[]{"Aeron", "ARN"});
        cryptoMap.put("propy", new String[]{"Propy", "PRO"});
        cryptoMap.put("belacoin", new String[]{"Bela", "BELA"});
        cryptoMap.put("novacoin", new String[]{"Novacoin", "NVC"});
        cryptoMap.put("rivetz", new String[]{"Rivetz", "RVT"});
        cryptoMap.put("pluton", new String[]{"Pluton", "PLU"});
        cryptoMap.put("earthcoin", new String[]{"EarthCoin", "EAC"});
        cryptoMap.put("sharechain", new String[]{"Sharechain", "SSS"});
        cryptoMap.put("bitcoin_plus", new String[]{"Bitcoin Plus", "XBC"});
        cryptoMap.put("internet_of_people", new String[]{"Internet of People", "IOP"});
        cryptoMap.put("auroracoin", new String[]{"Auroracoin", "AUR"});
        cryptoMap.put("xenon", new String[]{"Xenon", "XNN"});
        cryptoMap.put("masternodecoin", new String[]{"Masternodecoin", "MTNC"});
        cryptoMap.put("hellogold", new String[]{"HelloGold", "HGT"});
        cryptoMap.put("ecobit", new String[]{"Ecobit", "ECOB"});
        cryptoMap.put("clearpoll", new String[]{"ClearPoll", "POLL"});
        cryptoMap.put("dao_casino", new String[]{"DAO.Casino", "BET"});
        cryptoMap.put("investfeed", new String[]{"InvestFeed", "IFT"});
        cryptoMap.put("elixir", new String[]{"Elixir", "ELIX"});
        cryptoMap.put("oyster_pearl", new String[]{"Oyster Pearl", "PRL"});
        cryptoMap.put("qwark", new String[]{"Qwark", "QWARK"});
        cryptoMap.put("lampix", new String[]{"Lampix", "PIX"});
        cryptoMap.put("martexcoin", new String[]{"MarteXcoin", "MXT"});
        cryptoMap.put("blockcat", new String[]{"BlockCAT", "CAT"});
        cryptoMap.put("neutron", new String[]{"Neutron", "NTRN"});
        cryptoMap.put("zephyr", new String[]{"Zephyr", "ZEPH"});
        cryptoMap.put("dubaicoin_dbix", new String[]{"DubaiCoin", "DBIX"});
        cryptoMap.put("blockpool", new String[]{"Blockpool", "BPL"});
        cryptoMap.put("goldcoin", new String[]{"GoldCoin", "GLD"});
        cryptoMap.put("encryptotel", new String[]{"EncryptoTel [WAVES]", "ETT"});
        cryptoMap.put("project_decorum", new String[]{"Project Decorum", "PDC"});
        cryptoMap.put("paccoin", new String[]{"Paccoin", "PAC"});
        cryptoMap.put("lockchain", new String[]{"LockChain", "LOC"});
        cryptoMap.put("apx", new String[]{"APX", "APX"});
        cryptoMap.put("b2bx", new String[]{"B2B", "B2B"});
        cryptoMap.put("farad", new String[]{"Farad", "FRD"});
        cryptoMap.put("e_dinar_coin", new String[]{"E-Dinar Coin", "EDR"});
        cryptoMap.put("sexcoin", new String[]{"Sexcoin", "SXC"});
        cryptoMap.put("tao", new String[]{"Tao", "XTO"});
        cryptoMap.put("toacoin", new String[]{"ToaCoin", "TOA"});
        cryptoMap.put("veriumreserve", new String[]{"VeriumReserve", "VRM"});
        cryptoMap.put("dynamic", new String[]{"Dynamic", "DYN"});
        cryptoMap.put("trueflip", new String[]{"TrueFlip", "TFL"});
        cryptoMap.put("centurion", new String[]{"Centurion", "CNT"});
        cryptoMap.put("synergy", new String[]{"Synergy", "SNRG"});
        cryptoMap.put("cvcoin", new String[]{"CVCoin", "CVCOIN"});
        cryptoMap.put("riecoin", new String[]{"Riecoin", "RIC"});
        cryptoMap.put("espers", new String[]{"Espers", "ESP"});
        cryptoMap.put("prizm", new String[]{"PRIZM", "PZM"});
        cryptoMap.put("breakout_stake", new String[]{"Breakout Stake", "BRX"});
        cryptoMap.put("mybit_token", new String[]{"MyBit Token", "MYB"});
        cryptoMap.put("sportyfi", new String[]{"SportyFi", "SPF"});
        cryptoMap.put("mcap", new String[]{"MCAP", "MCAP"});
        cryptoMap.put("creditbit", new String[]{"Creditbit", "CRB"});
        cryptoMap.put("solaris", new String[]{"Solaris", "XLR"});
        cryptoMap.put("bitswift", new String[]{"Bitswift", "SWIFT"});
        cryptoMap.put("breakout", new String[]{"Breakout", "BRK"});
        cryptoMap.put("primalbase", new String[]{"Primalbase Token", "PBT"});
        cryptoMap.put("evergreencoin", new String[]{"EverGreenCoin", "EGC"});
        cryptoMap.put("trustplus", new String[]{"TrustPlus", "TRUST"});
        cryptoMap.put("startcoin", new String[]{"Startcoin", "START"});
        cryptoMap.put("geocoin", new String[]{"GeoCoin", "GEO"});
        cryptoMap.put("europecoin", new String[]{"EuropeCoin", "ERC"});
        cryptoMap.put("bitcloud", new String[]{"Bitcloud", "BTDX"});
        cryptoMap.put("bulwark", new String[]{"Bulwark", "BWK"});
        cryptoMap.put("cannabiscoin", new String[]{"CannabisCoin", "CANN"});
        cryptoMap.put("publica", new String[]{"Publica", "PBL"});
        cryptoMap.put("creativecoin", new String[]{"Creativecoin", "CREA"});
        cryptoMap.put("dovu", new String[]{"Dovu", "DOVU"});
        cryptoMap.put("bluecoin", new String[]{"BlueCoin", "BLU"});
        cryptoMap.put("bonpay", new String[]{"Bonpay", "BON"});
        cryptoMap.put("voisecom", new String[]{"Voise", "VOISE"});
        cryptoMap.put("mercury_protocol", new String[]{"Mercury Protocol", "GMT"});
        cryptoMap.put("chips", new String[]{"CHIPS", "CHIPS"});
        cryptoMap.put("hedge", new String[]{"Hedge", "HDG"});
        cryptoMap.put("gobyte", new String[]{"GoByte", "GBX"});
        cryptoMap.put("hyperstake", new String[]{"HyperStake", "HYP"});
        cryptoMap.put("flixxo", new String[]{"Flixxo", "FLIXX"});
        cryptoMap.put("yocoin", new String[]{"Yocoin", "YOC"});
        cryptoMap.put("dcorp", new String[]{"DCORP", "DRP"});
        cryptoMap.put("divi", new String[]{"Divi", "DIVX"});
        cryptoMap.put("huntercoin", new String[]{"HunterCoin", "HUC"});
        cryptoMap.put("ebtcnew", new String[]{"eBitcoin", "EBTC"});
        cryptoMap.put("colossuscoin_v2", new String[]{"Colossuscoin V2", "CV2"});
        cryptoMap.put("internxt", new String[]{"Internxt", "INXT"});
        cryptoMap.put("vslice", new String[]{"vSlice", "VSL"});
        cryptoMap.put("pirl", new String[]{"Pirl", "PIRL"});
        cryptoMap.put("zrcoin", new String[]{"ZrCoin", "ZRC"});
        cryptoMap.put("putincoin", new String[]{"PutinCoin", "PUT"});
        cryptoMap.put("intensecoin", new String[]{"IntenseCoin", "ITNS"});
        cryptoMap.put("parkbyte", new String[]{"ParkByte", "PKB"});
        cryptoMap.put("darcrus", new String[]{"Darcrus", "DAR"});
        cryptoMap.put("asiacoin", new String[]{"AsiaCoin", "AC"});
        cryptoMap.put("electra", new String[]{"Electra", "ECA"});
        cryptoMap.put("oceanlab", new String[]{"Oceanlab", "OCL"});
        cryptoMap.put("bitdeal", new String[]{"Bitdeal", "BDL"});
        cryptoMap.put("karbowanec", new String[]{"Karbo", "KRB"});
        cryptoMap.put("trezarcoin", new String[]{"TrezarCoin", "TZC"});
        cryptoMap.put("thegcccoin", new String[]{"TheGCCcoin", "GCC"});
        cryptoMap.put("indorse_token", new String[]{"Indorse Token", "IND"});
        cryptoMap.put("cryptoping", new String[]{"CryptoPing", "PING"});
        cryptoMap.put("zoin", new String[]{"Zoin", "ZOI"});
        cryptoMap.put("chaincoin", new String[]{"ChainCoin", "CHC"});
        cryptoMap.put("kolion", new String[]{"Kolion", "KLN"});
        cryptoMap.put("tokes", new String[]{"Tokes", "TKS"});
        cryptoMap.put("vtorrent", new String[]{"vTorrent", "VTR"});
        cryptoMap.put("crave", new String[]{"Crave", "CRAVE"});
        cryptoMap.put("real_estate_tokens", new String[]{"REX", "REX"});
        cryptoMap.put("sumokoin", new String[]{"Sumokoin", "SUMO"});
        cryptoMap.put("dnotes", new String[]{"DNotes", "NOTE"});
        cryptoMap.put("autonio", new String[]{"Autonio", "NIO"});
        cryptoMap.put("terracoin", new String[]{"Terracoin", "TRC"});
        cryptoMap.put("alqo", new String[]{"ALQO", "ALQO"});
        cryptoMap.put("cryptonite", new String[]{"Cryptonite", "XCN"});
        cryptoMap.put("spreadcoin", new String[]{"SpreadCoin", "SPR"});
        cryptoMap.put("magi", new String[]{"Magi", "XMG"});
        cryptoMap.put("adshares", new String[]{"AdShares", "ADST"});
        cryptoMap.put("starta", new String[]{"Starta", "STA"});
        cryptoMap.put("e_gulden", new String[]{"e-Gulden", "EFL"});
        cryptoMap.put("innova", new String[]{"Innova", "INN"});
        cryptoMap.put("ufo_coin", new String[]{"UFO Coin", "UFO"});
        cryptoMap.put("life", new String[]{"LIFE", "LIFE"});
        cryptoMap.put("real", new String[]{"REAL", "REAL"});
        cryptoMap.put("vivo", new String[]{"VIVO", "VIVO"});
        cryptoMap.put("hush", new String[]{"Hush", "HUSH"});
        cryptoMap.put("anoncoin", new String[]{"Anoncoin", "ANC"});
        cryptoMap.put("worldcoin", new String[]{"WorldCoin", "WDC"});
        cryptoMap.put("social", new String[]{"Social", "SCL"});
        cryptoMap.put("opus", new String[]{"Opus", "OPT"});
        cryptoMap.put("quark", new String[]{"Quark", "QRK"});
        cryptoMap.put("rupee", new String[]{"Rupee", "RUP"});
        cryptoMap.put("mywish", new String[]{"MyWish", "WISH"});
        cryptoMap.put("colossuscoinxt", new String[]{"ColossusCoinXT", "COLX"});
        cryptoMap.put("luxcoin", new String[]{"LUXCoin", "LUX"});
        cryptoMap.put("megacoin", new String[]{"Megacoin", "MEC"});
        cryptoMap.put("flypme", new String[]{"FlypMe", "FYP"});
        cryptoMap.put("fastcoin", new String[]{"Fastcoin", "FST"});
        cryptoMap.put("dotcoin", new String[]{"Dotcoin", "DOT"});
        cryptoMap.put("qvolta", new String[]{"Qvolta", "QVT"});
        cryptoMap.put("audiocoin", new String[]{"AudioCoin", "ADC"});
        cryptoMap.put("pandacoin_pnd", new String[]{"Pandacoin", "PND"});
        cryptoMap.put("crystal_clear", new String[]{"Crystal Clear ", "CCT"});
        cryptoMap.put("ico_openledger", new String[]{"ICO OpenLedger", "ICOO"});
        cryptoMap.put("equitrader", new String[]{"EquiTrader", "EQT"});
        cryptoMap.put("adelphoi", new String[]{"Adelphoi", "ADL"});
        cryptoMap.put("digipulse", new String[]{"DigiPulse", "DGPT"});
        cryptoMap.put("condensate", new String[]{"Condensate", "RAIN"});
        cryptoMap.put("smart_investment_fund_token", new String[]{"Smart Investment Fund Token", "SIFT"});
        cryptoMap.put("cartaxi_token", new String[]{"CarTaxi Token", "CTX"});
        cryptoMap.put("bitcoinz", new String[]{"BitcoinZ", "BTCZ"});
        cryptoMap.put("luckchain", new String[]{"LuckChain", "BASH"});
        cryptoMap.put("unitus", new String[]{"Unitus", "UIS"});
        cryptoMap.put("eboostcoin", new String[]{"eBoost", "EBST"});
        cryptoMap.put("legends_room", new String[]{"Legends Room", "LGD"});
        cryptoMap.put("sprouts", new String[]{"Sprouts", "SPRTS"});
        cryptoMap.put("pure", new String[]{"Pure", "PURE"});
        cryptoMap.put("atlant", new String[]{"ATLANT", "ATL"});
        cryptoMap.put("wavesgo", new String[]{"WavesGo", "WGO"});
        cryptoMap.put("linx", new String[]{"Linx", "LINX"});
        cryptoMap.put("onix", new String[]{"Onix", "ONX"});
        cryptoMap.put("fantomcoin", new String[]{"Fantomcoin", "FCN"});
        cryptoMap.put("embers", new String[]{"Embers", "MBRS"});
        cryptoMap.put("linda", new String[]{"Linda", "LINDA"});
        cryptoMap.put("vsync_vsx", new String[]{"Vsync", "VSX"});
        cryptoMap.put("arcticcoin", new String[]{"ArcticCoin", "ARC"});
        cryptoMap.put("bitcoin_red", new String[]{"Bitcoin Red", "BTCRED"});
        cryptoMap.put("octanox", new String[]{"Octanox", "OTX"});
        cryptoMap.put("hubii_network", new String[]{"Hubii Network", "HBT"});
        cryptoMap.put("erc20", new String[]{"ERC20", "ERC20"});
        cryptoMap.put("gcoin", new String[]{"GCoin", "GCN"});
        cryptoMap.put("flik", new String[]{"FLiK", "FLIK"});
        cryptoMap.put("bankcoin", new String[]{"Bankcoin", "B@"});
        cryptoMap.put("footy_cash", new String[]{"Footy Cash", "XFT"});
        cryptoMap.put("fundyourselfnow", new String[]{"FundYourselfNow", "FYN"});
        cryptoMap.put("neverdie", new String[]{"NEVERDIE", "NDC"});
        cryptoMap.put("goldblocks", new String[]{"GoldBlocks", "GB"});
        cryptoMap.put("visio", new String[]{"Visio", "VISIO"});
        cryptoMap.put("denarius_dnr", new String[]{"Denarius", "DNR"});
        cryptoMap.put("zeitcoin", new String[]{"Zeitcoin", "ZEIT"});
        cryptoMap.put("carboncoin", new String[]{"Carboncoin", "CARBON"});
        cryptoMap.put("magnet", new String[]{"Magnet", "MAG"});
        cryptoMap.put("swaptoken", new String[]{"SwapToken", "TOKEN"});
        cryptoMap.put("bytecent", new String[]{"Bytecent", "BYC"});
        cryptoMap.put("fujicoin", new String[]{"FujiCoin", "FJC"});
        cryptoMap.put("zennies", new String[]{"Zennies", "ZENI"});
        cryptoMap.put("campuscoin", new String[]{"CampusCoin", "CMPCO"});
        cryptoMap.put("ellaism", new String[]{"Ellaism", "ELLA"});
        cryptoMap.put("privatix", new String[]{"Privatix", "PRIX"});
        cryptoMap.put("cryptogenic_bullion", new String[]{"Crypto Bullion", "CBX"});
        cryptoMap.put("influxcoin", new String[]{"Influxcoin", "INFX"});
        cryptoMap.put("smileycoin", new String[]{"SmileyCoin", "SMLY"});
        cryptoMap.put("litedoge", new String[]{"LiteDoge", "LDOGE"});
        cryptoMap.put("noblecoin", new String[]{"NobleCoin", "NOBL"});
        cryptoMap.put("altcoin_alt", new String[]{"Altcoin", "ALT"});
        cryptoMap.put("piplcoin", new String[]{"PiplCoin", "PIPL"});
        cryptoMap.put("buzzcoin", new String[]{"BuzzCoin", "BUZZ"});
        cryptoMap.put("unify", new String[]{"Unify", "UNIFY"});
        cryptoMap.put("ethereum_movie_venture", new String[]{"Ethereum Movie Venture", "EMV"});
        cryptoMap.put("elementrem", new String[]{"Elementrem", "ELE"});
        cryptoMap.put("russiacoin", new String[]{"RussiaCoin", "RC"});
        cryptoMap.put("crowdcoin", new String[]{"CrowdCoin", "CRC"});
        cryptoMap.put("monacocoin", new String[]{"Monoeci", "XMCC"});
        cryptoMap.put("supercoin", new String[]{"SuperCoin", "SUPER"});
        cryptoMap.put("giga_watt_token", new String[]{"Giga Watt Token", "WTT"});
        cryptoMap.put("photon", new String[]{"Photon", "PHO"});
        cryptoMap.put("zetacoin", new String[]{"Zetacoin", "ZET"});
        cryptoMap.put("bitcoin_scrypt", new String[]{"Bitcoin Scrypt", "BTCS"});
        cryptoMap.put("coin", new String[]{"Coin(O)", "CNO"});
        cryptoMap.put("xgox", new String[]{"XGOX", "XGOX"});
        cryptoMap.put("procurrency", new String[]{"ProCurrency", "PROC"});
        cryptoMap.put("payfair", new String[]{"Payfair", "PFR"});
        cryptoMap.put("mazacoin", new String[]{"MazaCoin", "MZC"});
        cryptoMap.put("tracto", new String[]{"Tracto", "TRCT"});
        cryptoMap.put("canada_ecoin", new String[]{"Canada eCoin", "CDN"});
        cryptoMap.put("incakoin", new String[]{"IncaKoin", "NKA"});
        cryptoMap.put("orbitcoin", new String[]{"Orbitcoin", "ORB"});
        cryptoMap.put("redcoin", new String[]{"RedCoin", "RED"});
        cryptoMap.put("authorship", new String[]{"Authorship", "ATS"});
        cryptoMap.put("woodcoin", new String[]{"Woodcoin", "LOG"});
        cryptoMap.put("royal_kingdom_coin", new String[]{"Royal Kingdom Coin", "RKC"});
        cryptoMap.put("bata", new String[]{"Bata", "BTA"});
        cryptoMap.put("draftcoin", new String[]{"DraftCoin", "DFT"});
        cryptoMap.put("miners_reward_token", new String[]{"Miners' Reward Token", "MRT"});
        cryptoMap.put("hawala_today", new String[]{"Hawala.Today", "HAT"});
        cryptoMap.put("janus", new String[]{"Janus", "JNS"});
        cryptoMap.put("kobocoin", new String[]{"Kobocoin", "KOBO"});
        cryptoMap.put("monster_byte", new String[]{"Monster Byte", "MBI"});
        cryptoMap.put("renos", new String[]{"Renos", "RNS"});
        cryptoMap.put("britcoin", new String[]{"BritCoin", "BRIT"});
        cryptoMap.put("biblepay", new String[]{"BiblePay", "BBP"});
        cryptoMap.put("adzcoin", new String[]{"Adzcoin", "ADZ"});
        cryptoMap.put("kekcoin", new String[]{"KekCoin", "KEK"});
        cryptoMap.put("version", new String[]{"Version", "V"});
        cryptoMap.put("starcredits", new String[]{"StarCredits", "STRC"});
        cryptoMap.put("eltcoin", new String[]{"ELTCOIN", "ELTCOIN"});
        cryptoMap.put("zero", new String[]{"Zero", "ZER"});
        cryptoMap.put("trackr", new String[]{"CryptoInsight", "TKR"});
        cryptoMap.put("daxxcoin", new String[]{"DaxxCoin", "DAXX"});
        cryptoMap.put("capricoin", new String[]{"Capricoin", "CPC"});
        cryptoMap.put("gimli", new String[]{"Gimli", "GIM"});
        cryptoMap.put("skincoin", new String[]{"SkinCoin", "SKIN"});
        cryptoMap.put("growers_international", new String[]{"Growers International", "GRWI"});
        cryptoMap.put("nekonium", new String[]{"Nekonium", "NUKO"});
        cryptoMap.put("xios", new String[]{"Xios", "XIOS"});
        cryptoMap.put("bunnycoin", new String[]{"BunnyCoin", "BUN"});
        cryptoMap.put("bitbar", new String[]{"BitBar", "BTB"});
        cryptoMap.put("dinastycoin", new String[]{"Dinastycoin", "DCY"});
        cryptoMap.put("cream", new String[]{"Cream", "CRM"});
        cryptoMap.put("greencoin", new String[]{"Greencoin", "GRE"});
        cryptoMap.put("roulettetoken", new String[]{"RouletteToken", "RLT"});
        cryptoMap.put("ethbits", new String[]{"Ethbits", "ETBS"});
        cryptoMap.put("netcoin", new String[]{"NetCoin", "NET"});
        cryptoMap.put("titcoin", new String[]{"Titcoin", "TIT"});
        cryptoMap.put("dashcoin", new String[]{"Dashcoin", "DSH"});
        cryptoMap.put("digitalprice", new String[]{"DigitalPrice", "DP"});
        cryptoMap.put("signatum", new String[]{"Signatum", "SIGT"});
        cryptoMap.put("abjcoin", new String[]{"Abjcoin", "ABJ"});
        cryptoMap.put("unity_ingot", new String[]{"Unity Ingot", "UNY"});
        cryptoMap.put("upfiring", new String[]{"Upfiring", "UFR"});
        cryptoMap.put("eternity", new String[]{"Eternity", "ENT"});
        cryptoMap.put("joulecoin", new String[]{"Joulecoin", "XJO"});
        cryptoMap.put("teslacoin", new String[]{"TeslaCoin", "TES"});
        cryptoMap.put("fucktoken", new String[]{"FuckToken", "FUCK"});
        cryptoMap.put("hicoin", new String[]{"HiCoin", "XHI"});
        cryptoMap.put("joincoin", new String[]{"Joincoin", "J"});
        cryptoMap.put("deutsche_emark", new String[]{"Deutsche eMark", "DEM"});
        cryptoMap.put("aurumcoin", new String[]{"AurumCoin", "AU"});
        cryptoMap.put("insanecoin_insn", new String[]{"InsaneCoin", "INSN"});
        cryptoMap.put("netko", new String[]{"Netko", "NETKO"});
        cryptoMap.put("goodomy", new String[]{"Goodomy", "GOOD"});
        cryptoMap.put("bitradio", new String[]{"Bitradio", "BRO"});
        cryptoMap.put("remicoin", new String[]{"Remicoin", "RMC"});
        cryptoMap.put("lanacoin", new String[]{"LanaCoin", "LANA"});
        cryptoMap.put("shadowcash", new String[]{"ShadowCash", "SDC"});
        cryptoMap.put("machinecoin", new String[]{"Machinecoin", "MAC"});
        cryptoMap.put("cryptocarbon", new String[]{"CryptoCarbon", "CCRB"});
        cryptoMap.put("interstellar_holdings", new String[]{"Interstellar Holdings", "HOLD"});
        cryptoMap.put("fuelcoin", new String[]{"FuelCoin", "FC2"});
        cryptoMap.put("phoenixcoin", new String[]{"Phoenixcoin", "PXC"});
        cryptoMap.put("zozocoin", new String[]{"ZoZoCoin", "ZZC"});
        cryptoMap.put("copico", new String[]{"Copico", "XCPO"});
        cryptoMap.put("kittehcoin", new String[]{"Kittehcoin", "MEOW"});
        cryptoMap.put("piggycoin", new String[]{"Piggycoin", "PIGGY"});
        cryptoMap.put("scorecoin", new String[]{"Scorecoin", "SCORE"});
        cryptoMap.put("sovereign_hero", new String[]{"Sovereign Hero", "HERO"});
        cryptoMap.put("fluttercoin", new String[]{"FlutterCoin", "FLT"});
        cryptoMap.put("atomic_coin", new String[]{"Atomic Coin", "ATOM"});
        cryptoMap.put("the_cypherfunks", new String[]{"The Cypherfunks", "FUNK"});
        cryptoMap.put("veltor", new String[]{"Veltor", "VLT"});
        cryptoMap.put("tittiecoin", new String[]{"TittieCoin", "TTC"});
        cryptoMap.put("cryptojacks", new String[]{"Cryptojacks", "CJ"});
        cryptoMap.put("trollcoin", new String[]{"Trollcoin", "TROLL"});
        cryptoMap.put("desire", new String[]{"Desire", "DSR"});
        cryptoMap.put("unicoin", new String[]{"UniCoin", "UNIC"});
        cryptoMap.put("smartcoin", new String[]{"SmartCoin", "SMC"});
        cryptoMap.put("hobonickels", new String[]{"HoboNickels", "HBN"});
        cryptoMap.put("pioneer_coin", new String[]{"Pioneer Coin", "PCOIN"});
        cryptoMap.put("kushcoin", new String[]{"KushCoin", "KUSH"});
        cryptoMap.put("litecoin_plus", new String[]{"Litecoin Plus", "LCP"});
        cryptoMap.put("bigup", new String[]{"BigUp", "BIGUP"});
        cryptoMap.put("bitbtc", new String[]{"bitBTC", "BITBTC"});
        cryptoMap.put("maxcoin", new String[]{"MaxCoin", "MAX"});
        cryptoMap.put("accelerator_network", new String[]{"Accelerator Network", "ACC"});
        cryptoMap.put("moin", new String[]{"Moin", "MOIN"});
        cryptoMap.put("happycoin", new String[]{"Happycoin", "HPC"});
        cryptoMap.put("paycoin2", new String[]{"PayCoin", "XPY"});
        cryptoMap.put("minereum", new String[]{"Minereum", "MNE"});
        cryptoMap.put("postoken", new String[]{"PoSToken", "POS"});
        cryptoMap.put("swagbucks", new String[]{"SwagBucks", "BUCKS"});
        cryptoMap.put("tagcoin", new String[]{"TagCoin", "TAG"});
        cryptoMap.put("digital_developers_fund", new String[]{"DigitalDevelopersFund", "DDF"});
        cryptoMap.put("elcoin_el", new String[]{"Elcoin", "EL"});
        cryptoMap.put("lottocoin", new String[]{"LottoCoin", "LOT"});
        cryptoMap.put("spacecoin", new String[]{"SpaceCoin", "SPACE"});
        cryptoMap.put("confido", new String[]{"Confido", "CFD"});
        cryptoMap.put("guncoin", new String[]{"Guncoin", "GUN"});
        cryptoMap.put("tychocoin", new String[]{"Tychocoin", "TYCHO"});
        cryptoMap.put("digitalcoin", new String[]{"Digitalcoin", "DGC"});
        cryptoMap.put("mao_zedong", new String[]{"Mao Zedong", "MAO"});
        cryptoMap.put("bit20", new String[]{"Bit20", "BTWTY"});
        cryptoMap.put("altcommunity_coin", new String[]{"AltCommunity Coin", "ALTCOM"});
        cryptoMap.put("embercoin", new String[]{"EmberCoin", "EMB"});
        cryptoMap.put("nyancoin", new String[]{"Nyancoin", "NYAN"});
        cryptoMap.put("gameunits", new String[]{"GameUnits", "UNITS"});
        cryptoMap.put("fujinto", new String[]{"Fujinto", "NTO"});
        cryptoMap.put("inflationcoin", new String[]{"InflationCoin", "IFLT"});
        cryptoMap.put("bitcoinfast", new String[]{"Bitcoin Fast", "BCF"});
        cryptoMap.put("truckcoin", new String[]{"Truckcoin", "TRK"});
        cryptoMap.put("qubitcoin", new String[]{"QubitCoin", "Q2C"});
        cryptoMap.put("ethereum_gold", new String[]{"Ethereum Gold", "ETG"});
        cryptoMap.put("sterlingcoin", new String[]{"Sterlingcoin", "SLG"});
        cryptoMap.put("trumpcoin", new String[]{"TrumpCoin", "TRUMP"});
        cryptoMap.put("petrodollar", new String[]{"PetroDollar", "XPD"});
        cryptoMap.put("pakcoin", new String[]{"Pakcoin", "PAK"});
        cryptoMap.put("litebar", new String[]{"LiteBar", "LTB"});
        cryptoMap.put("starcash_network", new String[]{"StarCash Network", "STARS"});
        cryptoMap.put("ether_for_the_rest_of_the_world", new String[]{"E4ROW", "E4ROW"});
        cryptoMap.put("briacoin", new String[]{"BriaCoin", "BRIA"});
        cryptoMap.put("fincoin", new String[]{"FinCoin", "FNC"});
        cryptoMap.put("leviarcoin", new String[]{"LeviarCoin", "XLC"});
        cryptoMap.put("helleniccoin", new String[]{"Helleniccoin", "HNC"});
        cryptoMap.put("cannacoin", new String[]{"CannaCoin", "CCN"});
        cryptoMap.put("blakestar", new String[]{"BlakeStar", "BLAS"});
        cryptoMap.put("berncash", new String[]{"BERNcash", "BERN"});
        cryptoMap.put("macron", new String[]{"MACRON", "MCRN"});
        cryptoMap.put("ccore", new String[]{"Ccore", "CCO"});
        cryptoMap.put("ethereumcash", new String[]{"Ethereum Cash", "ECASH"});
        cryptoMap.put("bolivarcoin", new String[]{"Bolivarcoin", "BOLI"});
        cryptoMap.put("whalecoin", new String[]{"WhaleCoin", "WHL"});
        cryptoMap.put("pascal_lite", new String[]{"Pascal Lite", "PASL"});
        cryptoMap.put("mutual_coin", new String[]{"Mutual Coin", "MUT"});
        cryptoMap.put("kayicoin", new String[]{"Kayicoin", "KAYI"});
        cryptoMap.put("popularcoin", new String[]{"PopularCoin", "POP"});
        cryptoMap.put("postcoin", new String[]{"PostCoin", "POST"});
        cryptoMap.put("rimbit", new String[]{"Rimbit", "RBT"});
        cryptoMap.put("globalboost_y", new String[]{"GlobalBoost-Y", "BSTY"});
        cryptoMap.put("newbium", new String[]{"Newbium", "NEWB"});
        cryptoMap.put("goldreserve", new String[]{"GoldReserve", "XGR"});
        cryptoMap.put("bitsilver", new String[]{"bitSilver", "BITSILVER"});
        cryptoMap.put("triangles", new String[]{"Triangles", "TRI"});
        cryptoMap.put("hodlcoin", new String[]{"HOdlcoin", "HODL"});
        cryptoMap.put("platinumbar", new String[]{"PlatinumBAR", "XPTX"});
        cryptoMap.put("sugar_exchange", new String[]{"Sugar Exchange", "SGR"});
        cryptoMap.put("swing", new String[]{"Swing", "SWING"});
        cryptoMap.put("motocoin", new String[]{"Motocoin", "MOTO"});
        cryptoMap.put("chesscoin", new String[]{"ChessCoin", "CHESS"});
        cryptoMap.put("catcoin", new String[]{"Catcoin", "CAT"});
        cryptoMap.put("prototanium", new String[]{"Prototanium", "PR"});
        cryptoMap.put("icobid", new String[]{"ICOBID", "ICOB"});
        cryptoMap.put("hexx", new String[]{"Hexx", "HXX"});
        cryptoMap.put("senderon", new String[]{"Senderon", "SDRN"});
        cryptoMap.put("eot_token", new String[]{"EOT Token", "EOT"});
        cryptoMap.put("bitgem", new String[]{"Bitgem", "BTG"});
        cryptoMap.put("tattoocoin", new String[]{"Tattoocoin (Standard Edition)", "TSE"});
        cryptoMap.put("purevidz", new String[]{"PureVidz", "VIDZ"});
        cryptoMap.put("iethereum", new String[]{"iEthereum", "IETH"});
        cryptoMap.put("usde", new String[]{"USDe", "USDE"});
        cryptoMap.put("ratecoin", new String[]{"Ratecoin", "XRA"});
        cryptoMap.put("chancoin", new String[]{"ChanCoin", "4CHN"});
        cryptoMap.put("ecocoin", new String[]{"EcoCoin", "ECO"});
        cryptoMap.put("billionaire_token", new String[]{"Billionaire Token", "XBL"});
        cryptoMap.put("aricoin", new String[]{"Aricoin", "ARI"});
        cryptoMap.put("funcoin", new String[]{"FUNCoin", "FUNC"});
        cryptoMap.put("reecoin", new String[]{"ReeCoin", "REE"});
        cryptoMap.put("leacoin", new String[]{"LeaCoin", "LEA"});
        cryptoMap.put("cannation", new String[]{"Cannation", "CNNC"});
        cryptoMap.put("dalecoin", new String[]{"Dalecoin", "DALC"});
        cryptoMap.put("gapcoin", new String[]{"Gapcoin", "GAP"});
        cryptoMap.put("blazecoin", new String[]{"BlazeCoin", "BLZ"});
        cryptoMap.put("blakecoin", new String[]{"Blakecoin", "BLC"});
        cryptoMap.put("eaglecoin", new String[]{"EagleCoin", "EAGLE"});
        cryptoMap.put("mojocoin", new String[]{"MojoCoin", "MOJO"});
        cryptoMap.put("rasputin_online_coin", new String[]{"Rasputin Online Coin", "ROC"});
        cryptoMap.put("ripto_bux", new String[]{"Ripto Bux", "RBX"});
        cryptoMap.put("spots", new String[]{"Spots", "SPT"});
        cryptoMap.put("sagacoin", new String[]{"SagaCoin", "SAGA"});
        cryptoMap.put("virtacoinplus", new String[]{"Virtacoinplus", "XVP"});
        cryptoMap.put("ethereum_dark", new String[]{"Ethereum Dark", "ETHD"});
        cryptoMap.put("ebitcoin_cash", new String[]{"eBitcoinCash", "EBCH"});
        cryptoMap.put("theresa_may_coin", new String[]{"Theresa May Coin", "MAY"});
        cryptoMap.put("zcash_gold", new String[]{"ZCash Gold", "ZCG"});
        cryptoMap.put("sativacoin", new String[]{"Sativacoin", "STV"});
        cryptoMap.put("c_bit", new String[]{"C-Bit", "XCT"});
        cryptoMap.put("bumbacoin", new String[]{"BumbaCoin", "BUMBA"});
        cryptoMap.put("droxne", new String[]{"DROXNE", "DRXNE"});
        cryptoMap.put("grimcoin", new String[]{"Grimcoin", "GRIM"});
        cryptoMap.put("prime_xi", new String[]{"Prime-XI", "PXI"});
        cryptoMap.put("bitcoal", new String[]{"BitCoal", "COAL"});
        cryptoMap.put("monkey_project", new String[]{"Monkey Project", "MONK"});
        cryptoMap.put("virta_unique_coin", new String[]{"Virta Unique Coin", "VUC"});
        cryptoMap.put("metal_music_coin", new String[]{"Metal Music Coin", "MTLMC3"});
        cryptoMap.put("kurrent", new String[]{"Kurrent", "KURT"});
        cryptoMap.put("marijuanacoin", new String[]{"Marijuanacoin", "MAR"});
        cryptoMap.put("ronpaulcoin", new String[]{"RonPaulCoin", "RPC"});
        cryptoMap.put("chronos", new String[]{"Chronos", "CRX"});
        cryptoMap.put("coinonatx", new String[]{"CoinonatX", "XCXT"});
        cryptoMap.put("tekcoin", new String[]{"TEKcoin", "TEK"});
        cryptoMap.put("honey", new String[]{"Honey", "HONEY"});
        cryptoMap.put("bitgold", new String[]{"bitGold", "BITGOLD"});
        cryptoMap.put("aquariuscoin", new String[]{"AquariusCoin", "ARCO"});
        cryptoMap.put("globaltoken", new String[]{"GlobalToken", "GLT"});
        cryptoMap.put("gold_pressed_latinum", new String[]{"Gold Pressed Latinum", "GPL"});
        cryptoMap.put("iconic", new String[]{"Iconic", "ICON"});
        cryptoMap.put("solarflarecoin", new String[]{"Solarflarecoin", "SFC"});
        cryptoMap.put("soilcoin", new String[]{"SOILcoin", "SOIL"});
        cryptoMap.put("project_x", new String[]{"Project-X", "NANOX"});
        cryptoMap.put("sixeleven", new String[]{"SixEleven", "611"});
        cryptoMap.put("allion", new String[]{"Allion", "ALL"});
        cryptoMap.put("votecoin", new String[]{"VoteCoin", "VOT"});
        cryptoMap.put("boostcoin", new String[]{"BoostCoin", "BOST"});
        cryptoMap.put("biteur", new String[]{"bitEUR", "BITEUR"});
        cryptoMap.put("gpu_coin", new String[]{"GPU Coin", "GPU"});
        cryptoMap.put("neuro", new String[]{"Neuro", "NRO"});
        cryptoMap.put("aerium", new String[]{"Aerium", "AERM"});
        cryptoMap.put("interzone", new String[]{"Interzone", "ITZ"});
        cryptoMap.put("tajcoin", new String[]{"TajCoin", "TAJ"});
        cryptoMap.put("cachecoin", new String[]{"CacheCoin", "CACH"});
        cryptoMap.put("paycon", new String[]{"PayCon", "CON"});
        cryptoMap.put("x_coin", new String[]{"X-Coin", "XCO"});
        cryptoMap.put("kronecoin", new String[]{"Kronecoin", "KRONE"});
        cryptoMap.put("prcoin", new String[]{"PRCoin", "PRC"});
        cryptoMap.put("comet", new String[]{"Comet", "CMT"});
        cryptoMap.put("bitasean", new String[]{"BitAsean", "BAS"});
        cryptoMap.put("impact", new String[]{"Impact", "IMX"});
        cryptoMap.put("litecoin_ultra", new String[]{"LiteCoin Ultra", "LTCU"});
        cryptoMap.put("geertcoin", new String[]{"GeertCoin", "GEERT"});
        cryptoMap.put("anarchistsprime", new String[]{"AnarchistsPrime", "ACP"});
        cryptoMap.put("corgicoin", new String[]{"CorgiCoin", "CORG"});
        cryptoMap.put("litecred", new String[]{"Litecred", "LTCR"});
        cryptoMap.put("benjirolls", new String[]{"BenjiRolls", "BENJI"});
        cryptoMap.put("global_tour_coin", new String[]{"Global Tour Coin", "GTC"});
        cryptoMap.put("coinonat", new String[]{"Coinonat", "CXT"});
        cryptoMap.put("bnrtxcoin", new String[]{"BnrtxCoin", "BNX"});
        cryptoMap.put("wild_beast_block", new String[]{"Wild Beast Block", "WBB"});
        cryptoMap.put("exchangen", new String[]{"ExchangeN", "EXN"});
        cryptoMap.put("eryllium", new String[]{"Eryllium", "ERY"});
        cryptoMap.put("women", new String[]{"WomenCoin", "WOMEN"});
        cryptoMap.put("master_swiscoin", new String[]{"Master Swiscoin", "MSCN"});
        cryptoMap.put("playercoin", new String[]{"PlayerCoin", "PLACO"});
        cryptoMap.put("magnum", new String[]{"Magnum", "MGM"});
        cryptoMap.put("doubloon", new String[]{"BOAT", "BOAT"});
        cryptoMap.put("credence_coin", new String[]{"Credence Coin", "CRDNC"});
        cryptoMap.put("brat", new String[]{"BROTHER", "BRAT"});
        cryptoMap.put("litebitcoin", new String[]{"LiteBitcoin", "LBTC"});
        cryptoMap.put("vaperscoin", new String[]{"VapersCoin", "VPRC"});
        cryptoMap.put("veros", new String[]{"Veros", "VRS"});
        cryptoMap.put("roofs", new String[]{"Roofs", "ROOFS"});
        cryptoMap.put("ebittree_coin", new String[]{"Ebittree Coin", "EBT"});
        cryptoMap.put("argus", new String[]{"Argus", "ARGUS"});
        cryptoMap.put("crevacoin", new String[]{"CrevaCoin", "CREVA"});
        cryptoMap.put("cybcsec", new String[]{"CybCSec", "XCS"});
        cryptoMap.put("rawcoin2", new String[]{"Rawcoin", "XRC"});
        cryptoMap.put("levoplus", new String[]{"LevoPlus", "LVPS"});
        cryptoMap.put("harmonycoin_hmc", new String[]{"HarmonyCoin", "HMC"});
        cryptoMap.put("concoin", new String[]{"Concoin", "CONX"});
        cryptoMap.put("credo", new String[]{"Credo", "CREDO"});
        cryptoMap.put("stakecoin_stcn", new String[]{"Stakecoin", "STCN"});
        cryptoMap.put("e_coin", new String[]{"E-coin", "ECN"});
        cryptoMap.put("prospectors_gold", new String[]{"Prospectors Gold", "PGL"});
        cryptoMap.put("arcade_token", new String[]{"Arcade Token", "ARC"});
        cryptoMap.put("xcurrency", new String[]{"XCurrency", "XC"});
        cryptoMap.put("ergo", new String[]{"Ergo", "EFYT"});
        cryptoMap.put("unbreakablecoin", new String[]{"UnbreakableCoin", "UNB"});
        cryptoMap.put("ixcoin", new String[]{"Ixcoin", "IXC"});
        cryptoMap.put("smartbillions", new String[]{"SmartBillions", "SMART"});
        cryptoMap.put("yashcoin", new String[]{"YashCoin", "YASH"});
        cryptoMap.put("fimkrypto", new String[]{"FIMKrypto", "FIMK"});
        cryptoMap.put("inpay", new String[]{"InPay", "INPAY"});
        cryptoMap.put("ongsocial", new String[]{"onG.social", "ONG"});
        cryptoMap.put("cryptcoin", new String[]{"CryptCoin", "CRYPT"});
        cryptoMap.put("rustbits", new String[]{"Rustbits", "RUSTBITS"});
        cryptoMap.put("blockpay", new String[]{"BlockPay", "BLOCKPAY"});
        cryptoMap.put("hitcoin", new String[]{"HitCoin", "HTC"});
        cryptoMap.put("casino", new String[]{"Casino", "CASINO"});
        cryptoMap.put("shorty", new String[]{"Shorty", "SHORTY"});
        cryptoMap.put("emphy", new String[]{"Emphy", "EPY"});
        cryptoMap.put("link_platform", new String[]{"Link Platform", "LNK"});
        cryptoMap.put("intelligent_trading_tech", new String[]{"Intelligent Trading Tech", "ITT"});
        cryptoMap.put("ultimate_secure_cash", new String[]{"Ultimate Secure Cash", "USC"});
        cryptoMap.put("btsr", new String[]{"BTSR", "BTSR"});
        cryptoMap.put("ultracoin", new String[]{"UltraCoin", "UTC"});
        cryptoMap.put("bitboost", new String[]{"BitBoost", "BBT"});
        cryptoMap.put("ethbet", new String[]{"EthBet", "EBET"});
        cryptoMap.put("bowhead", new String[]{"Bowhead", "AHT"});
        cryptoMap.put("opal", new String[]{"Opal", "OPAL"});
        cryptoMap.put("etheriya", new String[]{"Etheriya", "RIYA"});
        cryptoMap.put("valorbit", new String[]{"Valorbit", "VAL"});
        cryptoMap.put("bitpark_coin", new String[]{"Bitpark Coin", "BPC"});
        cryptoMap.put("metalcoin", new String[]{"MetalCoin", "METAL"});
        cryptoMap.put("stress", new String[]{"Stress", "STS"});
        cryptoMap.put("cryptoforecast", new String[]{"CryptoForecast", "CFT"});
        cryptoMap.put("kilocoin", new String[]{"KiloCoin", "KLC"});
        cryptoMap.put("i0coin", new String[]{"I0Coin", "I0C"});
        cryptoMap.put("gaia", new String[]{"GAIA", "GAIA"});
        cryptoMap.put("universe", new String[]{"Universe", "UNI"});
        cryptoMap.put("shadow_token", new String[]{"Shadow Token", "SHDW"});
        cryptoMap.put("coin2_1", new String[]{"Coin2.1", "C2"});
        cryptoMap.put("sacoin", new String[]{"SACoin", "SAC"});
        cryptoMap.put("wayguide", new String[]{"WayGuide", "WAY"});
        cryptoMap.put("bitcurrency", new String[]{"Bitcurrency", "BTCR"});
        cryptoMap.put("icoin", new String[]{"iCoin", "ICN"});
        cryptoMap.put("bitstar", new String[]{"Bitstar", "BITS"});
        cryptoMap.put("iticoin", new String[]{"iTicoin", "ITI"});
        cryptoMap.put("zurcoin", new String[]{"Zurcoin", "ZUR"});
        cryptoMap.put("tigercoin", new String[]{"Tigercoin", "TGC"});
        cryptoMap.put("btctalkcoin", new String[]{"BTCtalkcoin", "TALK"});
        cryptoMap.put("sproutsextreme", new String[]{"SproutsExtreme", "SPEX"});
        cryptoMap.put("freicoin", new String[]{"Freicoin", "FRC"});
        cryptoMap.put("emerald", new String[]{"Emerald Crypto", "EMD"});
        cryptoMap.put("flycoin", new String[]{"Flycoin", "FLY"});
        cryptoMap.put("globalcoin", new String[]{"GlobalCoin", "GLC"});
        cryptoMap.put("mincoin", new String[]{"Mincoin", "MNC"});
        cryptoMap.put("ohm_wallet", new String[]{"OHM", "OHM"});
        cryptoMap.put("mineum", new String[]{"Mineum", "MNM"});
        cryptoMap.put("digicube", new String[]{"DigiCube", "CUBE"});
        cryptoMap.put("emoneypower", new String[]{"EMoneyPower", "EMP"});
        cryptoMap.put("shilling", new String[]{"Shilling", "SH"});
        cryptoMap.put("ganjacoin", new String[]{"GanjaCoin", "MRJA"});
        cryptoMap.put("bittokens", new String[]{"BitTokens", "BXT"});
        cryptoMap.put("sooncoin", new String[]{"SoonCoin", "SOON"});
        cryptoMap.put("halcyon", new String[]{"Halcyon", "HAL"});
        cryptoMap.put("bolenum", new String[]{"Bolenum", "BLN"});
        cryptoMap.put("satoshimadness", new String[]{"SatoshiMadness", "MAD"});
        cryptoMap.put("evil_coin", new String[]{"Evil Coin", "EVIL"});
        cryptoMap.put("cypher", new String[]{"Cypher", "CYP"});
        cryptoMap.put("wmcoin", new String[]{"WMCoin", "WMC"});
        cryptoMap.put("darsek", new String[]{"Darsek", "KED"});
        cryptoMap.put("wyvern", new String[]{"Wyvern", "WYV"});
        cryptoMap.put("ambercoin", new String[]{"AmberCoin", "AMBER"});
        cryptoMap.put("octocoin", new String[]{"OctoCoin", "888"});
        cryptoMap.put("slimcoin", new String[]{"Slimcoin", "SLM"});
        cryptoMap.put("yacoin", new String[]{"Yacoin", "YAC"});
        cryptoMap.put("quatloo", new String[]{"Quatloo", "QTL"});
        cryptoMap.put("philosopher_stones", new String[]{"Philosopher Stones", "PHS"});
        cryptoMap.put("evotion", new String[]{"Evotion", "EVO"});
        cryptoMap.put("rubies", new String[]{"Rubies", "RBIES"});
        cryptoMap.put("grantcoin", new String[]{"Grantcoin", "GRT"});
        cryptoMap.put("eurocoin", new String[]{"Eurocoin", "EUC"});
        cryptoMap.put("parallelcoin", new String[]{"ParallelCoin", "DUO"});
        cryptoMap.put("firecoin", new String[]{"Firecoin", "FIRE"});
        cryptoMap.put("hempcoin_hmp", new String[]{"HempCoin", "HMP"});
        cryptoMap.put("jetcoin", new String[]{"Jetcoin", "JET"});
        cryptoMap.put("songcoin", new String[]{"SongCoin", "SONG"});
        cryptoMap.put("acoin", new String[]{"Acoin", "ACOIN"});
        cryptoMap.put("px", new String[]{"PX", "PX"});
        cryptoMap.put("dollarcoin", new String[]{"Dollarcoin", "DLC"});
        cryptoMap.put("jin_coin", new String[]{"Jin Coin", "JIN"});
        cryptoMap.put("quazarcoin", new String[]{"QuazarCoin", "QCN"});
        cryptoMap.put("franko", new String[]{"Franko", "FRK"});
        cryptoMap.put("marscoin", new String[]{"Marscoin", "MARS"});
        cryptoMap.put("creatio", new String[]{"Creatio", "XCRE"});
        cryptoMap.put("revolvercoin", new String[]{"RevolverCoin", "XRE"});
        cryptoMap.put("islacoin", new String[]{"IslaCoin", "ISL"});
        cryptoMap.put("goldpieces", new String[]{"GoldPieces", "GP"});
        cryptoMap.put("independent_money_system", new String[]{"Independent Money System", "IMS"});
        cryptoMap.put("bitcoin_21", new String[]{"Bitcoin 21", "XBTC21"});
        cryptoMap.put("bitz", new String[]{"Bitz", "BITZ"});
        cryptoMap.put("virtualcoin", new String[]{"VirtualCoin", "VC"});
        cryptoMap.put("securecoin", new String[]{"SecureCoin", "SRC"});
        cryptoMap.put("antibitcoin", new String[]{"AntiBitcoin", "ANTI"});
        cryptoMap.put("nevacoin", new String[]{"NevaCoin", "NEVA"});
        cryptoMap.put("sling", new String[]{"Sling", "SLING"});
        cryptoMap.put("uro", new String[]{"Uro", "URO"});
        cryptoMap.put("idice", new String[]{"iDice", "ICE"});
        cryptoMap.put("debitcoin", new String[]{"Debitcoin", "DBTC"});
        cryptoMap.put("bitcoin_planet", new String[]{"Bitcoin Planet", "BTPL"});
        cryptoMap.put("allsafe", new String[]{"AllSafe", "ASAFE2"});
        cryptoMap.put("argentum", new String[]{"Argentum", "ARG"});
        cryptoMap.put("californium", new String[]{"Californium", "CF"});
        cryptoMap.put("dreamcoin", new String[]{"Dreamcoin", "DRM"});
        cryptoMap.put("cagecoin", new String[]{"CageCoin", "CAGE"});
        cryptoMap.put("unrealcoin", new String[]{"Unrealcoin", "URC"});
        cryptoMap.put("secretcoin", new String[]{"SecretCoin", "SCRT"});
        cryptoMap.put("ethgas", new String[]{"ETHGAS", "EGAS"});
        cryptoMap.put("guccionecoin", new String[]{"GuccioneCoin", "GCC"});
        cryptoMap.put("money", new String[]{"Money", "$$$"});
        cryptoMap.put("mustangcoin", new String[]{"MustangCoin", "MST"});
        cryptoMap.put("compucoin", new String[]{"CompuCoin", "CPN"});
        cryptoMap.put("ammo_rewards", new String[]{"Ammo Rewards", "AMMO"});
        cryptoMap.put("qibuck_asset", new String[]{"Qibuck Asset", "QBK"});
        cryptoMap.put("vector", new String[]{"VectorAI", "VEC2"});
        cryptoMap.put("mtmgaming", new String[]{"MTMGaming", "MTM"});
        cryptoMap.put("billarycoin", new String[]{"BillaryCoin", "BLRY"});
        cryptoMap.put("blackstar", new String[]{"Blackstar", "BSTAR"});
        cryptoMap.put("beavercoin", new String[]{"BeaverCoin", "BVC"});
        cryptoMap.put("crypto", new String[]{"Crypto", "CTO"});
        cryptoMap.put("cthulhu_offerings", new String[]{"Cthulhu Offerings", "OFF"});
        cryptoMap.put("zetamicron", new String[]{"ZetaMicron", "ZMC"});
        cryptoMap.put("luna_coin", new String[]{"Luna Coin", "LUNA"});
        cryptoMap.put("pulse", new String[]{"Pulse", "PULSE"});
        cryptoMap.put("warp", new String[]{"WARP", "WARP"});
        cryptoMap.put("rupaya", new String[]{"Rupaya", "RUPX"});
        cryptoMap.put("ereal", new String[]{"eREAL", "EREAL"});
        cryptoMap.put("agrolifecoin", new String[]{"AgrolifeCoin", "AGLC"});
        cryptoMap.put("mindcoin", new String[]{"MindCoin", "MND"});
        cryptoMap.put("flaxscript", new String[]{"Flaxscript", "FLAX"});
        cryptoMap.put("digital_rupees", new String[]{"Digital Rupees", "DRS"});
        cryptoMap.put("beatcoin", new String[]{"Beatcoin", "XBTS"});
        cryptoMap.put("printerium", new String[]{"Printerium", "PRX"});
        cryptoMap.put("bipcoin", new String[]{"BipCoin", "BIP"});
        cryptoMap.put("jewels", new String[]{"Jewels", "JWL"});
        cryptoMap.put("zayedcoin", new String[]{"Zayedcoin", "ZYD"});
        cryptoMap.put("flavorcoin", new String[]{"FlavorCoin", "FLVR"});
        cryptoMap.put("artex_coin", new String[]{"Artex Coin", "ATX"});
        cryptoMap.put("torcoin_tor", new String[]{"Torcoin", "TOR"});
        cryptoMap.put("gamebet_coin", new String[]{"GameBet Coin", "GBT"});
        cryptoMap.put("orlycoin", new String[]{"Orlycoin", "ORLY"});
        cryptoMap.put("dappster", new String[]{"DAPPSTER", "DLISK"});
        cryptoMap.put("dpay", new String[]{"DPAY", "DPAY"});
        cryptoMap.put("asiadigicoin", new String[]{"Asiadigicoin", "ADCN"});
        cryptoMap.put("piecoin", new String[]{"PIECoin", "PIE"});
        cryptoMap.put("bitquark", new String[]{"BitQuark", "BTQ"});
        cryptoMap.put("dibcoin", new String[]{"DIBCOIN", "DIBC"});
        cryptoMap.put("osmiumcoin", new String[]{"OsmiumCoin", "OS76"});
        cryptoMap.put("bowscoin", new String[]{"BowsCoin", "BSC"});
        cryptoMap.put("crtcoin", new String[]{"CRTCoin", "CRT"});
        cryptoMap.put("cryptoworldx_token", new String[]{"CryptoWorldX Token", "CWXT"});
        cryptoMap.put("ponzicoin", new String[]{"PonziCoin", "PONZI"});
        cryptoMap.put("fuzzballs", new String[]{"FuzzBalls", "FUZZ"});
        cryptoMap.put("ego", new String[]{"EGO", "EGO"});
        cryptoMap.put("steps", new String[]{"Steps", "STEPS"});
        cryptoMap.put("slevin", new String[]{"Slevin", "SLEVIN"});
        cryptoMap.put("healthywormcoin", new String[]{"HealthyWormCoin", "WORM"});
        cryptoMap.put("arbit", new String[]{"ARbit", "ARB"});
        cryptoMap.put("vip_tokens", new String[]{"VIP Tokens", "VIP"});
        cryptoMap.put("bios_crypto", new String[]{"BiosCrypto", "BIOS"});
        cryptoMap.put("network_token", new String[]{"Network Token", "NTWK"});
        cryptoMap.put("jobscoin", new String[]{"JobsCoin", "JOBS"});
        cryptoMap.put("milocoin", new String[]{"MiloCoin", "MILO"});
        cryptoMap.put("javascript_token", new String[]{"JavaScript Token", "JS"});
        cryptoMap.put("useless_ethereum_token", new String[]{"Useless Ethereum Token", "UET"});
        cryptoMap.put("ride_my_car", new String[]{"Ride My Car", "RIDE"});
        cryptoMap.put("cashcoin", new String[]{"Cashcoin", "CASH"});
        cryptoMap.put("plncoin", new String[]{"PLNcoin", "PLNC"});
        cryptoMap.put("kibicoin", new String[]{"KibiCoin", "KIC"});
        cryptoMap.put("dollar_online", new String[]{"Dollar Online", "DOLLAR"});
        cryptoMap.put("posex", new String[]{"PosEx", "PEX"});
        cryptoMap.put("vault_coin", new String[]{"Vault Coin", "VLTC"});
        cryptoMap.put("tagrcoin", new String[]{"TAGRcoin", "TAGR"});
        cryptoMap.put("impulsecoin", new String[]{"ImpulseCoin", "IMPS"});
        cryptoMap.put("high_voltage", new String[]{"High Voltage", "HVCO"});
        cryptoMap.put("braincoin", new String[]{"Braincoin", "BRAIN"});
        cryptoMap.put("chncoin", new String[]{"CHNCoin", "CNC"});
        cryptoMap.put("corethum", new String[]{"Corethum", "CRTM"});
        cryptoMap.put("destiny", new String[]{"Destiny", "DES"});
        cryptoMap.put("sydpak", new String[]{"SydPak", "SDP"});
        cryptoMap.put("zonecoin", new String[]{"Zonecoin", "ZNE"});
        cryptoMap.put("letitride", new String[]{"LetItRide", "LIR"});
        cryptoMap.put("futurexe", new String[]{"FuturXe", "FXE"});
        cryptoMap.put("ccminer", new String[]{"CCMiner", "CCM100"});
        cryptoMap.put("genstake", new String[]{"G3N", "G3N"});
        cryptoMap.put("speedcash", new String[]{"Speedcash", "SCS"});
        cryptoMap.put("antilitecoin", new String[]{"Antilitecoin", "ALTC"});
        cryptoMap.put("cryptoescudo", new String[]{"CryptoEscudo", "CESC"});
        cryptoMap.put("cabbage", new String[]{"Cabbage", "CAB"});
        cryptoMap.put("kingn_coin", new String[]{"KingN Coin", "KNC"});
        cryptoMap.put("elysium", new String[]{"Elysium", "ELS"});
        cryptoMap.put("burstocean", new String[]{"BurstOcean", "OCEAN"});
        cryptoMap.put("xonecoin", new String[]{"Xonecoin", "XOC"});
        cryptoMap.put("selfiecoin", new String[]{"Selfiecoin", "SLFI"});
        cryptoMap.put("bitvolt", new String[]{"Bitvolt", "VOLT"});
        cryptoMap.put("biobar", new String[]{"BioBar", "BIOB"});
        cryptoMap.put("rsgpcoin", new String[]{"RSGPcoin", "RSGP"});
        cryptoMap.put("gbcgoldcoin", new String[]{"GBCGoldCoin", "GBC"});
        cryptoMap.put("das", new String[]{"DAS", "DAS"});
        cryptoMap.put("morningstar_payments", new String[]{"MorningStar", "MRNG"});
        cryptoMap.put("frazcoin", new String[]{"Frazcoin", "FRAZ"});
        cryptoMap.put("socialcoin_socc", new String[]{"SocialCoin", "SOCC"});
        cryptoMap.put("save_and_gain", new String[]{"Save and Gain", "SANDG"});
        cryptoMap.put("ibank", new String[]{"iBank", "IBANK"});
        cryptoMap.put("coimatic_2", new String[]{"Coimatic 2.0", "CTIC2"});
        cryptoMap.put("tradecoin_v2", new String[]{"Tradecoin", "TRADE"});
        cryptoMap.put("coexistcoin", new String[]{"CoExistCoin", "COXST"});
        cryptoMap.put("geysercoin", new String[]{"GeyserCoin", "GSR"});
        cryptoMap.put("p7coin", new String[]{"P7Coin", "P7C"});
        cryptoMap.put("lex4all", new String[]{"Lex4All", "LEX"});
        cryptoMap.put("dix_asset", new String[]{"Dix Asset", "DIX"});
        cryptoMap.put("wallet_builders_coin", new String[]{"WalletBuildersCoin", "WBC"});
        cryptoMap.put("nodecoin", new String[]{"NodeCoin", "NODC"});
        cryptoMap.put("tristar_coin", new String[]{"Tristar Coin", "TSTR"});
        cryptoMap.put("ulatech", new String[]{"Ulatech", "ULA"});
        cryptoMap.put("sojourn", new String[]{"Sojourn", "SOJ"});
        cryptoMap.put("pizzacoin", new String[]{"PizzaCoin", "PIZZA"});
        cryptoMap.put("enigma", new String[]{"Enigma", "XNG"});
        cryptoMap.put("digital_credits", new String[]{"Digital Credits", "DGCS"});
        cryptoMap.put("abncoin", new String[]{"Abncoin", "ABN"});
        cryptoMap.put("mantracoin", new String[]{"MantraCoin", "MNC"});
        cryptoMap.put("digital_money_bits", new String[]{"Digital Money Bits", "DMB"});
        cryptoMap.put("environ", new String[]{"Environ", "ENV"});
        cryptoMap.put("caliphcoin", new String[]{"CaliphCoin", "CALC"});
        cryptoMap.put("falcoin", new String[]{"Falcoin", "FAL"});
        cryptoMap.put("future_digital_currency", new String[]{"Future Digital Currency", "FDC"});
        cryptoMap.put("applecoin_apw", new String[]{"AppleCoin", "APW"});
        cryptoMap.put("aelf", new String[]{"aelf", "ELF"});
        cryptoMap.put("icon", new String[]{"ICON", "ICX"});
        cryptoMap.put("bread", new String[]{"Bread", "BRD"});
        cryptoMap.put("wax", new String[]{"WAX", "WAX"});
        cryptoMap.put("atmcoin", new String[]{"ATMCoin", "ATMC"});
        cryptoMap.put("nubits", new String[]{"NuBits", "USNBT"});
        cryptoMap.put("clubcoin", new String[]{"ClubCoin", "CLUB"});
        cryptoMap.put("smartmesh", new String[]{"SmartMesh", "SMT"});
        cryptoMap.put("bibox_token", new String[]{"Bibox Token", "BIX"});
        cryptoMap.put("bitcoin_diamond", new String[]{"Bitcoin Diamond [Futures]", "BCD"});
        cryptoMap.put("comsa_eth", new String[]{"COMSA [ETH]", "CMS"});
        cryptoMap.put("energo", new String[]{"Energo", "TSL"});
        cryptoMap.put("gifto", new String[]{"Gifto", "GTO"});
        cryptoMap.put("cybermiles", new String[]{"CyberMiles", "CMT"});
        cryptoMap.put("dew", new String[]{"DEW", "DEW"});
        cryptoMap.put("bitcoinx", new String[]{"BitcoinX [Futures]", "BCX"});
        cryptoMap.put("magiccoin", new String[]{"MagicCoin", "MAGE"});
        cryptoMap.put("segwit2x", new String[]{"SegWit2x [Futures]", "B2X"});
        cryptoMap.put("poly_ai", new String[]{"POLY AI", "AI"});
        cryptoMap.put("comsa_xem", new String[]{"COMSA [XEM]", "CMS"});
        cryptoMap.put("iot_chain", new String[]{"IoT Chain", "ITC"});
        cryptoMap.put("ormeus_coin", new String[]{"Ormeus Coin", "ORME"});
        cryptoMap.put("tezos", new String[]{"Tezos (Pre-Launch)", "XTZ"});
        cryptoMap.put("naga", new String[]{"NAGA", "NGC"});
        cryptoMap.put("bt2_cst", new String[]{"BT2 [CST]", "BT2"});
        cryptoMap.put("viuly", new String[]{"Viuly", "VIU"});
        cryptoMap.put("win_coin", new String[]{"WINCOIN", "WC"});
        cryptoMap.put("fargocoin", new String[]{"Fargocoin", "FRGC"});
        cryptoMap.put("medibloc", new String[]{"Medibloc", "MED"});
        cryptoMap.put("infchain", new String[]{"InfChain", "INF"});
        cryptoMap.put("datum", new String[]{"Datum", "DAT"});
        cryptoMap.put("santa_coin", new String[]{"Santa Coin", "STC"});
        cryptoMap.put("genaro_network", new String[]{"Genaro Network", "GNX"});
        cryptoMap.put("ug_token", new String[]{"UG Token", "UGT"});
        cryptoMap.put("hollywoodcoin", new String[]{"HollyWoodCoin", "HWC"});
        cryptoMap.put("regalcoin", new String[]{"Regalcoin", "REC"});
        cryptoMap.put("bitsoar", new String[]{"BitSoar", "BSR"});
        cryptoMap.put("united_bitcoin", new String[]{"United Bitcoin", "UBTC"});
        cryptoMap.put("animecoin", new String[]{"Animecoin", "ANI"});
        cryptoMap.put("super_bitcoin", new String[]{"Super Bitcoin", "SBTC"});
        cryptoMap.put("prochain", new String[]{"ProChain", "PRO"});
        cryptoMap.put("filecoin", new String[]{"Filecoin [Futures]", "FIL"});
        cryptoMap.put("lltoken", new String[]{"LLToken", "LLT"});
        cryptoMap.put("qbao", new String[]{"Qbao", "QBT"});
        cryptoMap.put("bitserial", new String[]{"BitSerial", "BTE"});
        cryptoMap.put("snovio", new String[]{"Snovio", "SNOV"});
        cryptoMap.put("medishares", new String[]{"MediShares", "MDS"});
        cryptoMap.put("maker", new String[]{"Maker", "MKR"});
        cryptoMap.put("micromoney", new String[]{"MicroMoney", "AMM"});
        cryptoMap.put("sphre_air", new String[]{"Sphre AIR ", "XID"});
        cryptoMap.put("blockcdn", new String[]{"BlockCDN", "BCDN"});
        cryptoMap.put("gold_reward_token", new String[]{"GOLD Reward Token", "GRX"});
        cryptoMap.put("eroscoin", new String[]{"Eroscoin", "ERO"});
        cryptoMap.put("golos_gold", new String[]{"Golos Gold", "GBG"});
        cryptoMap.put("icon_futures", new String[]{"ICON [Futures]", "ICX"});
        cryptoMap.put("ea_coin", new String[]{"EA Coin", "EAG"});
        cryptoMap.put("donationcoin", new String[]{"Donationcoin", "DON"});
        cryptoMap.put("worldcore", new String[]{"Worldcore", "WRC"});
        cryptoMap.put("zengold", new String[]{"ZenGold", "ZENGOLD"});
        cryptoMap.put("strikebitclub", new String[]{"StrikeBitClub", "SBC"});
        cryptoMap.put("infinity_economics", new String[]{"Infinity Economics", "XIN"});
        cryptoMap.put("techshares", new String[]{"TechShares", "THS"});
        cryptoMap.put("safe_exchange_coin", new String[]{"Safe Exchange Coin", "SAFEX"});
        cryptoMap.put("davorcoin", new String[]{"DavorCoin", "DAV"});
        cryptoMap.put("dynamic_trading_rights", new String[]{"Dynamic Trading Rights", "DTR"});
        cryptoMap.put("bitcoin_unlimited", new String[]{"Bitcoin Unlimited (Futures)", "BTU"});
        cryptoMap.put("bitair", new String[]{"Bitair", "BTCA"});
        cryptoMap.put("playkey", new String[]{"Playkey", "PKT"});
        cryptoMap.put("stronghands", new String[]{"StrongHands", "SHND"});
        cryptoMap.put("cappasity", new String[]{"Cappasity", "CAPP"});
        cryptoMap.put("vpncoin", new String[]{"VPNCoin", "VASH"});
        cryptoMap.put("tokugawa", new String[]{"Tokugawa", "TOK"});
        cryptoMap.put("suretly", new String[]{"Suretly", "SUR"});
        cryptoMap.put("verify", new String[]{"Verify", "CRED"});
        cryptoMap.put("bt1_cst", new String[]{"BT1 [CST]", "BT1"});
        cryptoMap.put("b3coin", new String[]{"B3Coin", "B3"});
        cryptoMap.put("social_send", new String[]{"Social Send", "SEND"});
        cryptoMap.put("starbase", new String[]{"Starbase", "STAR"});
        cryptoMap.put("msd", new String[]{"MSD", "MSD"});
        cryptoMap.put("uquid_coin", new String[]{"Uquid Coin", "UQC"});
        cryptoMap.put("deuscoin", new String[]{"DeusCoin", "DEUS"});
        cryptoMap.put("plexcoin", new String[]{"PlexCoin", "PLX"});
        cryptoMap.put("ignis", new String[]{"Ignis [Futures]", "IGNIS"});
        cryptoMap.put("compcoin", new String[]{"Compcoin", "CMP"});
        cryptoMap.put("sigmacoin", new String[]{"SIGMAcoin", "SIGMA"});
        cryptoMap.put("kubera_coin", new String[]{"Kubera Coin", "KBR"});
        cryptoMap.put("flash", new String[]{"Flash", "FLASH"});
        cryptoMap.put("infinitecoin", new String[]{"Infinitecoin", "IFC"});
        cryptoMap.put("uahpay", new String[]{"UAHPay", "UAHPAY"});
        cryptoMap.put("topcoin", new String[]{"TopCoin", "TOP"});
        cryptoMap.put("mergecoin", new String[]{"MergeCoin", "MGC"});
        cryptoMap.put("glasscoin", new String[]{"GlassCoin", "GLS"});
        cryptoMap.put("blockchain_index", new String[]{"Blockchain Index", "BLX"});
        cryptoMap.put("force", new String[]{"FORCE", "FOR"});
        cryptoMap.put("t_coin", new String[]{"T-coin", "TCOIN"});
        cryptoMap.put("ox_fina", new String[]{"OX Fina", "OX"});
        cryptoMap.put("terranova", new String[]{"TerraNova", "TER"});
        cryptoMap.put("boscoin", new String[]{"BOScoin", "BOS"});
        cryptoMap.put("encryptotel_eth", new String[]{"EncryptoTel [ETH]", "ETT"});
        cryptoMap.put("btcmoon", new String[]{"BTCMoon", "BTCM"});
        cryptoMap.put("wild_crypto", new String[]{"Wild Crypto", "WILD"});
        cryptoMap.put("neo_gold", new String[]{"NEO GOLD", "NEOG"});
        cryptoMap.put("triaconta", new String[]{"Triaconta", "TRIA"});
        cryptoMap.put("sisa", new String[]{"SISA", "SISA"});
        cryptoMap.put("macro1", new String[]{"Macro", "MCR"});
        cryptoMap.put("litecoin_gold", new String[]{"LiteCoin Gold", "LTG"});
        cryptoMap.put("marxcoin", new String[]{"MarxCoin", "MARX"});
        cryptoMap.put("fapcoin", new String[]{"FAPcoin", "FAP"});
        cryptoMap.put("sand_coin", new String[]{"Sand Coin", "SND"});
        cryptoMap.put("student_coin", new String[]{"bitJob", "STU"});
        cryptoMap.put("dimoncoin", new String[]{"DimonCoin", "FUDD"});
        cryptoMap.put("ibtc", new String[]{"iBTC", "IBTC"});
        cryptoMap.put("netbit", new String[]{"netBit", "NBIT"});
        cryptoMap.put("adcoin", new String[]{"AdCoin", "ACC"});
        cryptoMap.put("hyper_tv", new String[]{"Hyper TV", "HYTV"});
        cryptoMap.put("minex", new String[]{"Minex", "MINEX"});
        cryptoMap.put("storjcoin_x", new String[]{"Storjcoin X", "SJCX"});
        cryptoMap.put("everus", new String[]{"Everus", "EVR"});
        cryptoMap.put("advanced_internet_blocks", new String[]{"Advanced Internet Blocks", "AIB"});
        cryptoMap.put("soma", new String[]{"Soma", "SCT"});
        cryptoMap.put("akuya_coin", new String[]{"Akuya Coin", "AKY"});
        cryptoMap.put("corion", new String[]{"CORION", "COR"});
        cryptoMap.put("chronologic", new String[]{"Chronologic", "DAY"});
        cryptoMap.put("peacecoin", new String[]{"Peacecoin", "PEC"});
        cryptoMap.put("quotient", new String[]{"Quotient", "XQN"});
        cryptoMap.put("ethereum_lite", new String[]{"Ethereum Lite", "ELITE"});
        cryptoMap.put("magnetcoin", new String[]{"Magnetcoin", "MAGN"});
        cryptoMap.put("pluscoin", new String[]{"PlusCoin", "PLC"});
        cryptoMap.put("tellurion", new String[]{"Tellurion", "TELL"});
        cryptoMap.put("batcoin", new String[]{"BatCoin", "BAT"});
        cryptoMap.put("bitcoin2x", new String[]{"Bitcoin2x", "BTC2X"});
        cryptoMap.put("digital_bullion_gold", new String[]{"Digital Bullion Gold", "DBG"});
        cryptoMap.put("cash_poker_pro", new String[]{"Cash Poker Pro", "CASH"});
        cryptoMap.put("bitcoin_silver", new String[]{"Bitcoin Silver", "BTCS"});
        cryptoMap.put("anryze", new String[]{"ANRYZE", "RYZ"});
        cryptoMap.put("royalties", new String[]{"Royalties", "XRY"});
        cryptoMap.put("rabbitcoin", new String[]{"RabbitCoin", "RBBT"});
        cryptoMap.put("fonziecoin", new String[]{"Fonziecoin", "FONZ"});
        cryptoMap.put("xylo", new String[]{"XYLO", "XYLO"});
        cryptoMap.put("zilbercoin", new String[]{"Zilbercoin", "ZBC"});
        cryptoMap.put("ur", new String[]{"UR", "UR"});
        cryptoMap.put("edrcoin", new String[]{"EDRCoin", "EDRC"});
        cryptoMap.put("wowcoin", new String[]{"Wowcoin", "WOW"});
        cryptoMap.put("natcoin", new String[]{"Natcoin", "NTC"});
        cryptoMap.put("sakuracoin", new String[]{"Sakuracoin", "SKR"});
        cryptoMap.put("vulcano", new String[]{"Vulcano", "VULC"});
        cryptoMap.put("landcoin", new String[]{"LandCoin", "LDCN"});
        cryptoMap.put("dfscoin", new String[]{"DFSCoin", "DFS"});
        cryptoMap.put("bitok", new String[]{"Bitok", "BITOK"});
        cryptoMap.put("runners", new String[]{"Runners", "RUNNERS"});
        cryptoMap.put("goldmaxcoin", new String[]{"GoldMaxCoin", "GMX"});
        cryptoMap.put("ties_network", new String[]{"TIES Network", "TIE"});
        cryptoMap.put("gaycoin", new String[]{"GAY Money", "GAY"});
        cryptoMap.put("mavro", new String[]{"Mavro", "MAVRO"});
        cryptoMap.put("mmxvi", new String[]{"MMXVI", "MMXVI"});
        cryptoMap.put("tattoocoin_limited", new String[]{"Tattoocoin (Limited Edition)", "TLE"});
        cryptoMap.put("exrnchain", new String[]{"EXRNchain", "EXRN"});
        cryptoMap.put("cubits", new String[]{"Cubits", "QBT"});
        cryptoMap.put("musiconomi", new String[]{"Musiconomi", "MCI"});
        cryptoMap.put("dynamiccoin", new String[]{"DynamicCoin", "DMC"});
        cryptoMap.put("yenten", new String[]{"YENTEN", "YTN"});
        cryptoMap.put("coupecoin", new String[]{"Coupecoin", "COUPE"});
        cryptoMap.put("universalroyalcoin", new String[]{"UniversalRoyalCoin", "UNRC"});
        cryptoMap.put("pabyosi_coin_special", new String[]{"Pabyosi Coin (Special)", "PCS"});
        cryptoMap.put("bastonet", new String[]{"Bastonet", "BSN"});
        cryptoMap.put("namocoin", new String[]{"NamoCoin", "NAMO"});
        cryptoMap.put("teslacoilcoin", new String[]{"TeslaCoilCoin", "TESLA"});
        cryptoMap.put("alphabitcoinfund", new String[]{"Alphabit", "ABC"});
        cryptoMap.put("india_coin", new String[]{"India Coin", "INDIA"});
        cryptoMap.put("internet_of_things", new String[]{"Internet of Things", "XOT"});
        cryptoMap.put("ocow", new String[]{"OCOW", "OCOW"});
        cryptoMap.put("antimatter", new String[]{"Antimatter", "ANTX"});
        cryptoMap.put("bestchain", new String[]{"BestChain", "BEST"});
        cryptoMap.put("amsterdamcoin", new String[]{"AmsterdamCoin", "AMS"});
        cryptoMap.put("francs", new String[]{"Francs", "FRN"});
        cryptoMap.put("lepen", new String[]{"LePen", "LEPEN"});
        cryptoMap.put("karmacoin", new String[]{"Karmacoin", "KARMA"});
        cryptoMap.put("protean", new String[]{"Protean", "PRN"});
        cryptoMap.put("iquant", new String[]{"iQuant", "IQT"});
        cryptoMap.put("phantomx", new String[]{"Phantomx", "PNX"});
        cryptoMap.put("trident", new String[]{"Trident Group", "TRDT"});
        cryptoMap.put("rublebit", new String[]{"RubleBit", "RUBIT"});
        cryptoMap.put("flappycoin", new String[]{"FlappyCoin", "FLAP"});
        cryptoMap.put("avatarcoin", new String[]{"AvatarCoin", "AV"});
        cryptoMap.put("eventchain", new String[]{"EventChain", "EVC"});
        cryptoMap.put("irishcoin", new String[]{"IrishCoin", "IRL"});
        cryptoMap.put("wa_space", new String[]{"WA Space", "WA"});
        cryptoMap.put("global_business_revolution", new String[]{"Global Business Revolution", "GBRC"});
        cryptoMap.put("golfcoin", new String[]{"Golfcoin", "GOLF"});
        cryptoMap.put("alpacoin", new String[]{"AlpaCoin", "APC"});
        cryptoMap.put("skeincoin", new String[]{"Skeincoin", "SKC"});
        cryptoMap.put("topaz", new String[]{"Topaz Coin", "TOPAZ"});
        cryptoMap.put("snakeeyes", new String[]{"SnakeEyes", "SNAKE"});
        cryptoMap.put("bitcedi", new String[]{"Bitcedi", "BXC"});
        cryptoMap.put("coimatic_3", new String[]{"Coimatic 3.0", "CTIC3"});
        cryptoMap.put("sharkcoin", new String[]{"Sharkcoin", "SAK"});
        cryptoMap.put("cybercoin", new String[]{"CyberCoin", "CC"});
        cryptoMap.put("egold", new String[]{"eGold", "EGOLD"});
        cryptoMap.put("wi_coin", new String[]{"Wi Coin", "WIC"});
        cryptoMap.put("aces", new String[]{"Aces", "ACES"});
        cryptoMap.put("elacoin", new String[]{"Elacoin", "ELC"});
        cryptoMap.put("happy_creator_coin", new String[]{"Happy Creator Coin", "HCC"});
        cryptoMap.put("dutch_coin", new String[]{"Dutch Coin", "DUTCH"});
        cryptoMap.put("shacoin", new String[]{"SHACoin", "SHA"});
        cryptoMap.put("gulfcoin", new String[]{"GulfCoin", "MGC"});
        cryptoMap.put("halloween_coin", new String[]{"Halloween Coin", "HALLO"});
        cryptoMap.put("first_bitcoin", new String[]{"First Bitcoin", "BIT"});
        cryptoMap.put("ebit", new String[]{"eBIT", "EBIT"});
        cryptoMap.put("wink", new String[]{"Wink", "WINK"});
        cryptoMap.put("pirate_blocks", new String[]{"Pirate Blocks", "SKULL"});
        cryptoMap.put("swapcoin", new String[]{"Swapcoin", "SWP"});
        cryptoMap.put("eusd", new String[]{"eUSD", "EUSD"});
        cryptoMap.put("quebecoin", new String[]{"Quebecoin", "QBC"});
        cryptoMap.put("granitecoin", new String[]{"Granite", "GRN"});
        cryptoMap.put("safecoin", new String[]{"SafeCoin", "SFE"});
        cryptoMap.put("stex", new String[]{"STEX", "STEX"});
        cryptoMap.put("primulon", new String[]{"Primulon", "PRIMU"});
        cryptoMap.put("qora", new String[]{"Qora", "QORA"});
        cryptoMap.put("dashs", new String[]{"Dashs", "DASHS"});
        cryptoMap.put("dubstep", new String[]{"Dubstep", "DUB"});
        cryptoMap.put("yellow_token", new String[]{"Yellow Token", "YEL"});
        cryptoMap.put("wearesatoshi", new String[]{"WeAreSatoshi", "WSX"});
        cryptoMap.put("zsecoin", new String[]{"ZSEcoin", "ZSE"});
        cryptoMap.put("moneta2", new String[]{"Moneta", "MONETA"});
        cryptoMap.put("cycling_coin", new String[]{"Cycling Coin", "CYC"});
        cryptoMap.put("cyder", new String[]{"Cyder", "CYDER"});
        cryptoMap.put("bongger", new String[]{"Bongger", "BGR"});
        cryptoMap.put("international_diamond", new String[]{"International Diamond", "XID"});
        cryptoMap.put("yescoin", new String[]{"Yescoin", "YES"});
        cryptoMap.put("regacoin", new String[]{"Regacoin", "REGA"});
        cryptoMap.put("sync", new String[]{"Sync", "SYNC"});
        cryptoMap.put("bubble", new String[]{"Bubble", "BUB"});
        cryptoMap.put("axiom", new String[]{"Axiom", "AXIOM"});
        cryptoMap.put("avoncoin", new String[]{"Avoncoin", "ACN"});
        cryptoMap.put("bitbase", new String[]{"Bitbase", "BTBc"});
        cryptoMap.put("rhfcoin", new String[]{"RHFCoin", "RHFC"});
        cryptoMap.put("thecreed", new String[]{"TheCreed", "TCR"});
        cryptoMap.put("uncoin", new String[]{"UNCoin", "UNC"});
        cryptoMap.put("moneycoin", new String[]{"MoneyCoin", "MONEY"});
        cryptoMap.put("hodl_bucks", new String[]{"HODL Bucks", "HDLB"});
        cryptoMap.put("birds", new String[]{"Birds", "BIRDS"});
        cryptoMap.put("deltacredits", new String[]{"DeltaCredits", "DCRE"});
        cryptoMap.put("voyacoin", new String[]{"Voyacoin", "VOYA"});
        cryptoMap.put("clinton", new String[]{"Clinton", "CLINT"});
        cryptoMap.put("futcoin", new String[]{"FutCoin", "FUTC"});
        cryptoMap.put("rcoin", new String[]{"Rcoin", "RCN"});
        cryptoMap.put("the_vegan_initiative", new String[]{"The Vegan Initiative", "XVE"});
        cryptoMap.put("kashhcoin", new String[]{"KashhCoin", "KASHH"});
        cryptoMap.put("blazercoin", new String[]{"BlazerCoin", "BLAZR"});
        cryptoMap.put("psilocybin", new String[]{"Psilocybin", "PSY"});
        cryptoMap.put("president_trump", new String[]{"President Trump", "PRES"});
        cryptoMap.put("first_bitcoin_capital", new String[]{"First Bitcoin Capital", "BITCF"});
        cryptoMap.put("facecoin", new String[]{"Facecoin", "FC"});
        cryptoMap.put("xaucoin", new String[]{"Xaucoin", "XAU"});
        cryptoMap.put("royalcoin", new String[]{"RoyalCoin", "ROYAL"});
        cryptoMap.put("prismchain", new String[]{"PrismChain", "PRM"});
        cryptoMap.put("goldunioncoin", new String[]{"GoldUnionCoin", "GUC"});
        cryptoMap.put("richcoin", new String[]{"RichCoin", "RICHX"});
        cryptoMap.put("hyper", new String[]{"Hyper", "HYPER"});
        cryptoMap.put("betacoin", new String[]{"BetaCoin", "BET"});
        cryptoMap.put("lazaruscoin", new String[]{"Lazaruscoin", "LAZ"});
        cryptoMap.put("safe_trade_coin", new String[]{"Safe Trade Coin", "XSTC"});
        cryptoMap.put("paypeer", new String[]{"PayPeer", "PAYP"});
        cryptoMap.put("trickycoin", new String[]{"TrickyCoin", "TRICK"});
        cryptoMap.put("high_gain", new String[]{"High Gain", "HIGH"});
        cryptoMap.put("fazzcoin", new String[]{"Fazzcoin", "FAZZ"});
        cryptoMap.put("cbd_crystals", new String[]{"CBD Crystals", "CBD"});
        cryptoMap.put("rupaya_old", new String[]{"Rupaya [OLD]", "RUPX"});
        cryptoMap.put("turbocoin", new String[]{"TurboCoin", "TURBO"});
        cryptoMap.put("xtd_coin", new String[]{"XTD Coin", "XTD"});
        cryptoMap.put("huncoin", new String[]{"Huncoin", "HNC"});
        cryptoMap.put("operand", new String[]{"Operand", "OP"});
        cryptoMap.put("eltc", new String[]{"eLTC", "ELTC2"});
        cryptoMap.put("mobilecash", new String[]{"MobileCash", "MBL"});
        cryptoMap.put("omicron", new String[]{"Omicron", "OMC"});
        cryptoMap.put("pinkdog", new String[]{"PinkDog", "PDG"});
        cryptoMap.put("utacoin", new String[]{"UtaCoin", "UTA"});
        cryptoMap.put("pokecoin", new String[]{"PokeCoin", "POKE"});
        cryptoMap.put("infinity_pay", new String[]{"Infinity Pay", "IPY"});
        cryptoMap.put("linkedcoin", new String[]{"LinkedCoin", "LKC"});
        cryptoMap.put("todaycoin", new String[]{"TodayCoin", "TODAY"});
        cryptoMap.put("frankywillcoin", new String[]{"FrankyWillCoin", "FRWC"});
        cryptoMap.put("ugain", new String[]{"UGAIN", "GAIN"});
        cryptoMap.put("teamup", new String[]{"TeamUp", "TEAM"});
        cryptoMap.put("sportscoin", new String[]{"SportsCoin", "SPORT"});
        cryptoMap.put("cashme", new String[]{"Cashme", "CME"});
        cryptoMap.put("lathaan", new String[]{"LAthaan", "LTH"});
        cryptoMap.put("teracoin", new String[]{"TeraCoin", "TERA"});
        cryptoMap.put("bitcentavo", new String[]{"BitCentavo", "NBE"});
        cryptoMap.put("vegascoin", new String[]{"VegasCoin", "VGC"});
        cryptoMap.put("gameleaguecoin", new String[]{"GameLeagueCoin", "GML"});
        cryptoMap.put("fireflycoin", new String[]{"FireFlyCoin", "FFC"});
        cryptoMap.put("eggcoin", new String[]{"EggCoin", "EGG"});
        cryptoMap.put("shellcoin", new String[]{"ShellCoin", "SHELL"});
        cryptoMap.put("invisiblecoin", new String[]{"InvisibleCoin", "IVZ"});
        cryptoMap.put("x2", new String[]{"X2", "X2"});
        cryptoMap.put("opescoin", new String[]{"Opescoin", "OPES"});
        cryptoMap.put("bitalphacoin", new String[]{"BitAlphaCoin", "BAC"});
        cryptoMap.put("darklisk", new String[]{"DarkLisk", "DISK"});
        cryptoMap.put("president_johnson", new String[]{"President Johnson", "GARY"});
        cryptoMap.put("xde_ii", new String[]{"XDE II", "XDE2"});
        cryptoMap.put("bixc", new String[]{"BIXC", "BIXC"});
        cryptoMap.put("tyrocoin", new String[]{"Tyrocoin", "TYC"});
        cryptoMap.put("picoin", new String[]{"PiCoin", "PI"});
        cryptoMap.put("aidos_kuneen", new String[]{"Aidos Kuneen", "ADK"});
        cryptoMap.put("cheapcoin", new String[]{"Cheapcoin", "CHEAP"});
        cryptoMap.put("peepcoin", new String[]{"PeepCoin", "PCN"});
        cryptoMap.put("peoplecoin", new String[]{"PeopleCoin", "MEN"});
        cryptoMap.put("aseancoin", new String[]{"Aseancoin", "ASN"});
        cryptoMap.put("bitfid", new String[]{"BITFID", "FID"});
        cryptoMap.put("bitcoincashscrypt", new String[]{"BitcoinCashScrypt", "BCCS"});
        cryptoMap.put("casinocoin", new String[]{"CasinoCoin", "CSC"});
        cryptoMap.put("etherdoge", new String[]{"EtherDoge", "EDOGE"});
        cryptoMap.put("faceblock", new String[]{"Faceblock", "FBL"});
    }
}
